import { describe,expect,it,vi } from 'vitest'
import { SettingsRequestError,settingsPermissions,type Dictionary,type Setting,type SettingsClient,type SettingsPermissionCode } from '@go-admin/domain-settings'
import { createSettingsController } from './settings-controller'
const setting:Setting={id:'10000000-0000-4000-8000-000000000001',category:'business',key:'shop.title',label:'Shop',value:'Title',description:'',enabled:true,revision:1}
const dictionary:Dictionary={id:'20000000-0000-4000-8000-000000000001',key:'order.status',name:'Order status',description:'',enabled:true,revision:1}
const client=():SettingsClient=>({listSettings:vi.fn().mockResolvedValue({rows:[setting],total:1}),createSetting:vi.fn().mockResolvedValue(setting),updateSetting:vi.fn().mockResolvedValue({...setting,revision:2}),deleteSetting:vi.fn().mockResolvedValue(undefined),listDictionaries:vi.fn().mockResolvedValue({rows:[dictionary],total:1}),createDictionary:vi.fn().mockResolvedValue(dictionary),updateDictionary:vi.fn().mockResolvedValue({...dictionary,revision:2}),deleteDictionary:vi.fn().mockResolvedValue(undefined),listItems:vi.fn().mockResolvedValue({rows:[],total:0}),createItem:vi.fn(),updateItem:vi.fn(),deleteItem:vi.fn(),options:vi.fn().mockResolvedValue([])})
const capabilities=()=>{const values=new Set<SettingsPermissionCode>(Object.values(settingsPermissions));let scope='all';return{can:(code:SettingsPermissionCode)=>values.has(code),scope:()=>scope,revoke:(code:SettingsPermissionCode)=>values.delete(code),setScope:(value:string)=>{scope=value}}}
describe('settings controller',()=>{
  it('uses shared list projection and hides it immediately on capability or scope revoke',async()=>{const api=client(),port=capabilities(),controller=createSettingsController(api,async()=>true,port);await controller.settings.refresh();expect(controller.settings.snapshot().rows).toEqual([setting]);port.revoke(settingsPermissions.valuesRead);expect(controller.settings.snapshot().rows).toEqual([]);expect(controller.can(settingsPermissions.valuesWrite)).toBe(false);port.setScope('self');expect(controller.settings.snapshot().total).toBe(0)})
  it.each(['relogin','forbidden','unavailable'] as const)('fails closed after current %s list failure',async category=>{const api=client(),port=capabilities(),controller=createSettingsController(api,async()=>true,port);await controller.settings.refresh();vi.mocked(api.listSettings).mockRejectedValueOnce(new SettingsRequestError(category));await expect(controller.settings.search({search:'next'})).rejects.toBeInstanceOf(SettingsRequestError);expect(controller.failure()).toBe(category);expect(controller.settings.snapshot().rows).toEqual([])})
  it('never repeats a successful write while projection repair retries',async()=>{const api=client(),port=capabilities(),controller=createSettingsController(api,async()=>true,port);await controller.settings.refresh();vi.mocked(api.listSettings).mockRejectedValueOnce(new SettingsRequestError('unavailable')).mockRejectedValueOnce(new SettingsRequestError('unavailable')).mockResolvedValueOnce({rows:[setting],total:1});expect(await controller.saveSetting({category:'business',key:'shop.title',label:'Shop',value:'Title',description:'',enabled:true})).toBe('refresh-failed');expect(await controller.saveSetting({category:'business',key:'other.key',label:'Other',value:'Other',description:'',enabled:true})).toBe('refresh-failed');expect(api.createSetting).toHaveBeenCalledTimes(1);expect(await controller.repairProjection()).toBe('refresh-failed');expect(await controller.repairProjection()).toBe('completed');expect(api.createSetting).toHaveBeenCalledTimes(1)})
  it('confirms destructive writes and preserves stable failures',async()=>{const api=client(),port=capabilities(),confirm=vi.fn().mockResolvedValue(false),controller=createSettingsController(api,confirm,port);await controller.settings.refresh();expect(await controller.removeSetting(setting)).toBe('cancelled');expect(api.deleteSetting).not.toHaveBeenCalled();confirm.mockResolvedValue(true);vi.mocked(api.deleteSetting).mockRejectedValueOnce(new SettingsRequestError('conflict'));expect(await controller.removeSetting(setting)).toBe('failed');expect(controller.failure()).toBe('conflict')})
  it('rechecks permission after deferred confirmation before any write',async()=>{let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve}),api=client(),port=capabilities(),controller=createSettingsController(api,async()=>{await gate;return true},port);await controller.settings.refresh();const pending=controller.removeSetting(setting);port.revoke(settingsPermissions.valuesDelete);release();expect(await pending).toBe('failed');expect(controller.failure()).toBe('forbidden');expect(api.deleteSetting).not.toHaveBeenCalled()})
  it('reconciles an updated or deleted selected dictionary after projection refresh',async()=>{const api=client(),port=capabilities(),controller=createSettingsController(api,async()=>true,port);await controller.dictionaries.refresh();await controller.selectDictionary(dictionary);vi.mocked(api.listDictionaries).mockResolvedValueOnce({rows:[{...dictionary,name:'Updated',revision:2}],total:1});expect(await controller.saveDictionary({...dictionary,name:'Updated'})).toBe('completed');expect(controller.dictionary()).toEqual(expect.objectContaining({name:'Updated',revision:2}));vi.mocked(api.listDictionaries).mockResolvedValueOnce({rows:[],total:0});expect(await controller.removeDictionary({...dictionary,name:'Updated',revision:2})).toBe('completed');expect(controller.dictionary()).toBeNull()})
  it('rolls back category and dictionary selections when their projections fail',async()=>{const api=client(),port=capabilities(),controller=createSettingsController(api,async()=>true,port);await controller.settings.refresh();vi.mocked(api.listSettings).mockRejectedValueOnce(new SettingsRequestError('unavailable'));await expect(controller.selectCategory('ui')).rejects.toBeInstanceOf(SettingsRequestError);expect(controller.category()).toBe('business');await controller.dictionaries.refresh();await controller.selectDictionary(dictionary);const replacement={...dictionary,id:'20000000-0000-4000-8000-000000000002',key:'other.status'};vi.mocked(api.listItems).mockRejectedValueOnce(new SettingsRequestError('unavailable'));await expect(controller.selectDictionary(replacement)).rejects.toBeInstanceOf(SettingsRequestError);expect(controller.dictionary()).toEqual(dictionary)})
})
