<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { settingsPermissions,type Dictionary,type DictionaryInput,type DictionaryItem,type DictionaryItemInput,type DictionaryOption,type Setting,type SettingInput } from '@go-admin/domain-settings'
import type { SettingsController } from './settings-controller'
const props=defineProps<{controller:SettingsController}>();const emit=defineEmits<{sessionRequired:[];forbidden:[]}>();const revision=ref(0),tab=ref<'business'|'ui'|'dictionaries'>('business'),search=ref(''),itemSearch=ref(''),options=ref<ReadonlyArray<DictionaryOption>>([])
const settingForm=reactive<SettingInput&{id?:string;revision?:number}>(props.controller.emptySetting()),dictionaryForm=reactive<DictionaryInput&{id?:string;revision?:number}>(props.controller.emptyDictionary()),itemForm=reactive<DictionaryItemInput&{id?:string;revision?:number}>(props.controller.emptyItem())
const settings=computed(()=>{void revision.value;return props.controller.settings.snapshot()}),dictionaries=computed(()=>{void revision.value;return props.controller.dictionaries.snapshot()}),items=computed(()=>{void revision.value;return props.controller.items.snapshot()}),failure=computed(()=>{void revision.value;return props.controller.failure()}),blocked=computed(()=>{void revision.value;return props.controller.busy||props.controller.pendingRepair})
const can=(code:Parameters<SettingsController['can']>[0])=>{void revision.value;return props.controller.can(code)}
const settle=async(operation:()=>Promise<unknown>)=>{try{await operation()}catch{}finally{revision.value+=1;if(props.controller.failure()==='relogin')emit('sessionRequired');if(props.controller.failure()==='forbidden')emit('forbidden')}}
const switchTab=(value:typeof tab.value)=>settle(async()=>{tab.value=value;search.value='';if(value==='business'||value==='ui')await props.controller.selectCategory(value);else await props.controller.dictionaries.refresh()})
const editSetting=(row:Setting)=>Object.assign(settingForm,{category:row.category,key:row.key,label:row.label,value:row.value,description:row.description,enabled:row.enabled,id:row.id,revision:row.revision})
const resetSetting=()=>{Object.assign(settingForm,props.controller.emptySetting());delete settingForm.id;delete settingForm.revision}
const saveSetting=()=>settle(async()=>{const result=await props.controller.saveSetting({...settingForm});if(result==='completed'||result==='failed')resetSetting()})
const editDictionary=(row:Dictionary)=>Object.assign(dictionaryForm,{key:row.key,name:row.name,description:row.description,enabled:row.enabled,id:row.id,revision:row.revision})
const resetDictionary=()=>{Object.assign(dictionaryForm,props.controller.emptyDictionary());delete dictionaryForm.id;delete dictionaryForm.revision}
const selectDictionary=(row:Dictionary)=>settle(async()=>{await props.controller.selectDictionary(row);options.value=await props.controller.options(row.key)})
const editItem=(row:DictionaryItem)=>Object.assign(itemForm,{value:row.value,label:row.label,sortOrder:row.sortOrder,enabled:row.enabled,id:row.id,revision:row.revision})
const resetItem=()=>{Object.assign(itemForm,props.controller.emptyItem());delete itemForm.id;delete itemForm.revision}
const refreshOptions=async()=>{const selected=props.controller.dictionary();options.value=selected?await props.controller.options(selected.key):[]}
const saveDictionary=()=>settle(async()=>{if(await props.controller.saveDictionary({...dictionaryForm})==='completed'){resetDictionary();await refreshOptions()}})
const saveItem=()=>settle(async()=>{if(await props.controller.saveItem({...itemForm})==='completed'){resetItem();await refreshOptions()}})
const removeItem=(row:DictionaryItem)=>settle(async()=>{if(await props.controller.removeItem(row)==='completed')await refreshOptions()})
onMounted(()=>{void settle(()=>props.controller.settings.refresh())})
</script>
<template>
  <section class="settings-page" aria-labelledby="settings-title">
    <header><div><h1 id="settings-title">Settings</h1><p>Business configuration and reference data</p></div><button v-if="controller.pendingRepair" data-testid="repair" :disabled="controller.busy" @click="settle(()=>controller.repairProjection())">Refresh results</button><button v-else-if="failure==='unavailable'" @click="settle(()=>tab==='dictionaries'?controller.dictionaries.refresh():controller.settings.refresh())">Retry</button></header>
    <p v-if="failure" role="alert" :data-failure="failure">{{ failure }}</p>
    <nav aria-label="Settings views"><button data-testid="tab-business" :aria-pressed="tab==='business'" @click="switchTab('business')">Business</button><button data-testid="tab-ui" :aria-pressed="tab==='ui'" @click="switchTab('ui')">Interface</button><button data-testid="tab-dictionaries" :aria-pressed="tab==='dictionaries'" @click="switchTab('dictionaries')">Dictionaries</button></nav>
    <template v-if="tab!=='dictionaries'&&can(settingsPermissions.valuesRead)">
      <form class="search" @submit.prevent="settle(()=>controller.settings.search({search}))"><label>Search <input v-model="search" name="setting-search"></label><button :disabled="blocked">Search</button><button type="button" :disabled="blocked" @click="search='';settle(()=>controller.settings.reset())">Reset</button></form>
      <div class="workspace"><div class="table"><table><thead><tr><th>Key</th><th>Label</th><th>Value</th><th>Enabled</th><th>Actions</th></tr></thead><tbody><tr v-for="row in settings.rows" :key="row.id"><td>{{row.key}}</td><td>{{row.label}}</td><td>{{row.value}}</td><td>{{row.enabled?'Yes':'No'}}</td><td><button v-if="can(settingsPermissions.valuesWrite)" :data-testid="`edit-setting-${row.key}`" :disabled="blocked" @click="editSetting(row)">Edit</button><button v-if="can(settingsPermissions.valuesDelete)" :data-testid="`delete-setting-${row.key}`" :disabled="blocked" @click="settle(()=>controller.removeSetting(row))">Delete</button></td></tr></tbody></table></div>
        <form v-if="can(settingsPermissions.valuesWrite)" data-testid="setting-form" @submit.prevent="saveSetting"><h2>{{settingForm.id?'Edit':'Create'}} setting</h2><label>Key <input v-model="settingForm.key" name="setting-key" required></label><label>Label <input v-model="settingForm.label" name="setting-label" required></label><label>Value <textarea v-model="settingForm.value" name="setting-value" required></textarea></label><label>Description <textarea v-model="settingForm.description" name="setting-description"></textarea></label><label><input v-model="settingForm.enabled" name="setting-enabled" type="checkbox"> Enabled</label><button data-testid="save-setting" :disabled="blocked">Save</button><button type="button" @click="resetSetting">Cancel</button></form></div>
    </template>
    <template v-if="tab==='dictionaries'&&can(settingsPermissions.dictionariesRead)">
      <form class="search" @submit.prevent="settle(()=>controller.dictionaries.search({search}))"><label>Search <input v-model="search" name="dictionary-search"></label><button :disabled="blocked">Search</button><button type="button" @click="search='';settle(()=>controller.dictionaries.reset())">Reset</button></form>
      <div class="workspace"><div class="table"><table><thead><tr><th>Key</th><th>Name</th><th>Enabled</th><th>Actions</th></tr></thead><tbody><tr v-for="row in dictionaries.rows" :key="row.id"><td><button :data-testid="`select-dictionary-${row.key}`" @click="selectDictionary(row)">{{row.key}}</button></td><td>{{row.name}}</td><td>{{row.enabled?'Yes':'No'}}</td><td><button v-if="can(settingsPermissions.dictionariesWrite)" :data-testid="`edit-dictionary-${row.key}`" @click="editDictionary(row)">Edit</button><button v-if="can(settingsPermissions.dictionariesDelete)" :data-testid="`delete-dictionary-${row.key}`" @click="settle(()=>controller.removeDictionary(row))">Delete</button></td></tr></tbody></table></div>
        <form v-if="can(settingsPermissions.dictionariesWrite)" data-testid="dictionary-form" @submit.prevent="saveDictionary"><h2>{{dictionaryForm.id?'Edit':'Create'}} dictionary</h2><label>Key <input v-model="dictionaryForm.key" name="dictionary-key" required></label><label>Name <input v-model="dictionaryForm.name" name="dictionary-name" required></label><label>Description <textarea v-model="dictionaryForm.description" name="dictionary-description"></textarea></label><label><input v-model="dictionaryForm.enabled" name="dictionary-enabled" type="checkbox"> Enabled</label><button data-testid="save-dictionary" :disabled="blocked">Save</button><button type="button" @click="resetDictionary">Cancel</button></form></div>
      <section v-if="controller.dictionary()" class="items" data-testid="dictionary-items"><h2>{{controller.dictionary()?.name}} items</h2><form class="search" @submit.prevent="settle(()=>controller.items.search({search:itemSearch}))"><label>Search <input v-model="itemSearch" name="item-search"></label><button data-testid="search-items">Search</button><button type="button" @click="itemSearch='';settle(()=>controller.items.reset())">Reset</button></form><table><thead><tr><th>Value</th><th>Label</th><th>Order</th><th>Enabled</th><th>Actions</th></tr></thead><tbody><tr v-for="row in items.rows" :key="row.id"><td>{{row.value}}</td><td>{{row.label}}</td><td>{{row.sortOrder}}</td><td>{{row.enabled?'Yes':'No'}}</td><td><button v-if="can(settingsPermissions.dictionariesWrite)" :data-testid="`edit-item-${row.value}`" @click="editItem(row)">Edit</button><button v-if="can(settingsPermissions.dictionariesDelete)" :data-testid="`delete-item-${row.value}`" @click="removeItem(row)">Delete</button></td></tr></tbody></table>
        <form v-if="can(settingsPermissions.dictionariesWrite)" data-testid="item-form" @submit.prevent="saveItem"><label>Value <input v-model="itemForm.value" name="item-value" required></label><label>Label <input v-model="itemForm.label" name="item-label" required></label><label>Order <input v-model.number="itemForm.sortOrder" name="item-order" type="number" min="0" max="100000"></label><label><input v-model="itemForm.enabled" name="item-enabled" type="checkbox"> Enabled</label><button data-testid="save-item" :disabled="blocked">Save item</button></form><p data-testid="enabled-options">Enabled options: {{options.map(value=>value.label).join(', ')}}</p></section>
    </template>
  </section>
</template>
<style scoped>
.settings-page{display:grid;gap:16px;color:#17202a}header,nav,.search{display:flex;align-items:end;justify-content:space-between;gap:10px}h1,h2,p{margin:0}.workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);gap:18px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #dfe6e9;text-align:left}form{display:grid;align-content:start;gap:8px}label{display:grid;gap:4px}button,input,textarea{font:inherit}[role=alert]{padding:8px;border-left:3px solid #b42318;background:#fff1f0}.items{display:grid;gap:10px;border-top:1px solid #dfe6e9;padding-top:14px}@media(max-width:720px){.workspace{grid-template-columns:1fr}header,nav,.search{flex-wrap:wrap}}
</style>
