<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { settingsPermissions,type Dictionary,type DictionaryInput,type DictionaryItem,type DictionaryItemInput,type DictionaryOption,type Setting,type SettingInput } from '@go-admin/domain-settings'
import type { SettingsController } from './settings-controller'
const props=defineProps<{controller:SettingsController}>();const emit=defineEmits<{sessionRequired:[];forbidden:[]}>();const revision=ref(0),tab=ref<'business'|'ui'|'dictionaries'>('business'),search=ref(''),itemSearch=ref(''),options=ref<ReadonlyArray<DictionaryOption>>([]),settingFormOpen=ref(false),dictionaryFormOpen=ref(false),itemFormOpen=ref(false)
const settingForm=reactive<SettingInput&{id?:string;revision?:number}>(props.controller.emptySetting()),dictionaryForm=reactive<DictionaryInput&{id?:string;revision?:number}>(props.controller.emptyDictionary()),itemForm=reactive<DictionaryItemInput&{id?:string;revision?:number}>(props.controller.emptyItem())
const settings=computed(()=>{void revision.value;return props.controller.settings.snapshot()}),dictionaries=computed(()=>{void revision.value;return props.controller.dictionaries.snapshot()}),items=computed(()=>{void revision.value;return props.controller.items.snapshot()}),failure=computed(()=>{void revision.value;return props.controller.failure()}),blocked=computed(()=>{void revision.value;return props.controller.busy||props.controller.pendingRepair})
const can=(code:Parameters<SettingsController['can']>[0])=>{void revision.value;return props.controller.can(code)}
const settle=async(operation:()=>Promise<unknown>)=>{try{await operation()}catch{}finally{revision.value+=1;if(props.controller.failure()==='relogin')emit('sessionRequired');if(props.controller.failure()==='forbidden')emit('forbidden')}}
const closeForms=()=>{settingFormOpen.value=false;dictionaryFormOpen.value=false;itemFormOpen.value=false;resetSetting();resetDictionary();resetItem()}
const switchTab=(value:typeof tab.value)=>settle(async()=>{closeForms();if(value==='business'||value==='ui')await props.controller.selectCategory(value);else await props.controller.dictionaries.refresh();tab.value=value;search.value=''})
const openSetting=()=>{resetSetting();settingFormOpen.value=true}
const editSetting=(row:Setting)=>{Object.assign(settingForm,{category:row.category,key:row.key,label:row.label,value:row.value,description:row.description,enabled:row.enabled,id:row.id,revision:row.revision});settingFormOpen.value=true}
const resetSetting=()=>{Object.assign(settingForm,props.controller.emptySetting());delete settingForm.id;delete settingForm.revision}
const saveSetting=()=>settle(async()=>{const outcome=await props.controller.saveSetting({...settingForm});if(outcome==='completed'){resetSetting();settingFormOpen.value=false}else if(outcome==='failed'&&props.controller.failure()==='validation')resetSetting()})
const openDictionary=()=>{resetDictionary();dictionaryFormOpen.value=true}
const editDictionary=(row:Dictionary)=>{Object.assign(dictionaryForm,{key:row.key,name:row.name,description:row.description,enabled:row.enabled,id:row.id,revision:row.revision});dictionaryFormOpen.value=true}
const resetDictionary=()=>{Object.assign(dictionaryForm,props.controller.emptyDictionary());delete dictionaryForm.id;delete dictionaryForm.revision}
const selectDictionary=(row:Dictionary)=>settle(async()=>{await props.controller.selectDictionary(row);options.value=await props.controller.options(row.key)})
const openItem=()=>{resetItem();itemFormOpen.value=true}
const editItem=(row:DictionaryItem)=>{Object.assign(itemForm,{value:row.value,label:row.label,sortOrder:row.sortOrder,enabled:row.enabled,id:row.id,revision:row.revision});itemFormOpen.value=true}
const resetItem=()=>{Object.assign(itemForm,props.controller.emptyItem());delete itemForm.id;delete itemForm.revision}
const refreshOptions=async()=>{const selected=props.controller.dictionary();options.value=selected?await props.controller.options(selected.key):[]}
const saveDictionary=()=>settle(async()=>{if(await props.controller.saveDictionary({...dictionaryForm})==='completed'){resetDictionary();dictionaryFormOpen.value=false;await refreshOptions()}})
const saveItem=()=>settle(async()=>{if(await props.controller.saveItem({...itemForm})==='completed'){resetItem();itemFormOpen.value=false;await refreshOptions()}})
const removeItem=(row:DictionaryItem)=>settle(async()=>{if(await props.controller.removeItem(row)==='completed')await refreshOptions()})
onMounted(()=>{void settle(()=>props.controller.settings.refresh())})
</script>
<template>
  <section class="settings-page" aria-labelledby="settings-title">
    <header><div><h1 id="settings-title">系统设置</h1><p>维护业务参数、界面设置和字典数据</p></div><button v-if="controller.pendingRepair" data-testid="repair" :disabled="controller.busy" @click="settle(()=>controller.repairProjection())">刷新结果</button><button v-else-if="failure==='unavailable'" @click="settle(()=>tab==='dictionaries'?controller.dictionaries.refresh():controller.settings.refresh())">重试</button></header>
    <p v-if="failure" role="alert" :data-failure="failure">设置操作未能完成，请检查权限和提交内容后重试。</p>
    <nav aria-label="设置视图"><button data-testid="tab-business" :aria-pressed="tab==='business'" :disabled="blocked" @click="switchTab('business')">业务参数</button><button data-testid="tab-ui" :aria-pressed="tab==='ui'" :disabled="blocked" @click="switchTab('ui')">界面设置</button><button data-testid="tab-dictionaries" :aria-pressed="tab==='dictionaries'" :disabled="blocked" @click="switchTab('dictionaries')">字典管理</button></nav>
    <template v-if="tab!=='dictionaries'&&can(settingsPermissions.valuesRead)">
      <form class="search" @submit.prevent="settle(()=>controller.settings.search({search}))"><label>参数搜索<input v-model="search" name="setting-search" placeholder="请输入参数键或名称"></label><button :disabled="blocked">搜索</button><button type="button" :disabled="blocked" @click="search='';settle(()=>controller.settings.reset())">重置</button><button v-if="can(settingsPermissions.valuesWrite)" type="button" data-testid="open-setting-form" :disabled="blocked" @click="openSetting">新增</button></form>
      <div class="workspace"><div class="table"><table><thead><tr><th>参数键</th><th>参数名称</th><th>参数值</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in settings.rows" :key="row.id"><td>{{row.key}}</td><td>{{row.label}}</td><td>{{row.value}}</td><td>{{row.enabled?'启用':'停用'}}</td><td><button v-if="can(settingsPermissions.valuesWrite)" :data-testid="`edit-setting-${row.key}`" data-action="edit" :disabled="blocked" @click="editSetting(row)">修改</button><button v-if="can(settingsPermissions.valuesDelete)" :data-testid="`delete-setting-${row.key}`" data-action="delete" :disabled="blocked" @click="settle(()=>controller.removeSetting(row))">删除</button></td></tr></tbody></table></div></div>
      <div v-if="settingFormOpen && can(settingsPermissions.valuesWrite)" class="management-dialog-backdrop" @click.self="settingFormOpen=false;resetSetting()" @keydown.esc="settingFormOpen=false;resetSetting()"><form class="management-dialog" data-testid="setting-form" role="dialog" aria-modal="true" aria-labelledby="setting-form-title" @submit.prevent="saveSetting"><header class="management-dialog__header"><h2 id="setting-form-title">{{settingForm.id?'修改':'新增'}}参数</h2><button type="button" aria-label="关闭" @click="settingFormOpen=false;resetSetting()">×</button></header><div class="management-dialog__body"><label>参数键<input v-model="settingForm.key" name="setting-key" autofocus required></label><label>参数名称<input v-model="settingForm.label" name="setting-label" required></label><label>参数值<textarea v-model="settingForm.value" name="setting-value" required></textarea></label><label>说明<textarea v-model="settingForm.description" name="setting-description"></textarea></label><label class="choice"><input v-model="settingForm.enabled" name="setting-enabled" type="checkbox">启用</label></div><footer class="management-dialog__footer"><button type="button" @click="settingFormOpen=false;resetSetting()">取消</button><button data-testid="save-setting" :disabled="blocked">保存</button></footer></form></div>
    </template>
    <template v-if="tab==='dictionaries'&&can(settingsPermissions.dictionariesRead)">
      <form class="search" @submit.prevent="settle(()=>controller.dictionaries.search({search}))"><label>字典搜索<input v-model="search" name="dictionary-search" placeholder="请输入字典编码或名称"></label><button :disabled="blocked">搜索</button><button type="button" @click="search='';settle(()=>controller.dictionaries.reset())">重置</button><button v-if="can(settingsPermissions.dictionariesWrite)" type="button" data-testid="open-dictionary-form" @click="openDictionary">新增</button></form>
      <div class="workspace"><div class="table"><table><thead><tr><th>字典编码</th><th>字典名称</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in dictionaries.rows" :key="row.id"><td><button :data-testid="`select-dictionary-${row.key}`" @click="selectDictionary(row)">{{row.key}}</button></td><td>{{row.name}}</td><td>{{row.enabled?'启用':'停用'}}</td><td><button v-if="can(settingsPermissions.dictionariesWrite)" :data-testid="`edit-dictionary-${row.key}`" data-action="edit" @click="editDictionary(row)">修改</button><button v-if="can(settingsPermissions.dictionariesDelete)" :data-testid="`delete-dictionary-${row.key}`" data-action="delete" @click="settle(()=>controller.removeDictionary(row))">删除</button></td></tr></tbody></table></div></div>
      <div v-if="dictionaryFormOpen && can(settingsPermissions.dictionariesWrite)" class="management-dialog-backdrop" @click.self="dictionaryFormOpen=false;resetDictionary()" @keydown.esc="dictionaryFormOpen=false;resetDictionary()"><form class="management-dialog" data-testid="dictionary-form" role="dialog" aria-modal="true" aria-labelledby="dictionary-form-title" @submit.prevent="saveDictionary"><header class="management-dialog__header"><h2 id="dictionary-form-title">{{dictionaryForm.id?'修改':'新增'}}字典</h2><button type="button" aria-label="关闭" @click="dictionaryFormOpen=false;resetDictionary()">×</button></header><div class="management-dialog__body"><label>字典编码<input v-model="dictionaryForm.key" name="dictionary-key" autofocus required></label><label>字典名称<input v-model="dictionaryForm.name" name="dictionary-name" required></label><label>说明<textarea v-model="dictionaryForm.description" name="dictionary-description"></textarea></label><label class="choice"><input v-model="dictionaryForm.enabled" name="dictionary-enabled" type="checkbox">启用</label></div><footer class="management-dialog__footer"><button type="button" @click="dictionaryFormOpen=false;resetDictionary()">取消</button><button data-testid="save-dictionary" :disabled="blocked">保存</button></footer></form></div>
      <section v-if="controller.dictionary()" class="items" data-testid="dictionary-items"><h2>{{controller.dictionary()?.name}} 字典数据</h2><form class="search" @submit.prevent="settle(()=>controller.items.search({search:itemSearch}))"><label>字典项搜索<input v-model="itemSearch" name="item-search"></label><button data-testid="search-items">搜索</button><button type="button" @click="itemSearch='';settle(()=>controller.items.reset())">重置</button><button v-if="can(settingsPermissions.dictionariesWrite)" type="button" data-testid="open-item-form" @click="openItem">新增</button></form><table><thead><tr><th>字典值</th><th>显示标签</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in items.rows" :key="row.id"><td>{{row.value}}</td><td>{{row.label}}</td><td>{{row.sortOrder}}</td><td>{{row.enabled?'启用':'停用'}}</td><td><button v-if="can(settingsPermissions.dictionariesWrite)" :data-testid="`edit-item-${row.value}`" data-action="edit" @click="editItem(row)">修改</button><button v-if="can(settingsPermissions.dictionariesDelete)" :data-testid="`delete-item-${row.value}`" data-action="delete" @click="removeItem(row)">删除</button></td></tr></tbody></table>
        <p data-testid="enabled-options">已启用选项：{{options.map(value=>value.label).join(', ')}}</p><div v-if="itemFormOpen && can(settingsPermissions.dictionariesWrite)" class="management-dialog-backdrop" @click.self="itemFormOpen=false;resetItem()" @keydown.esc="itemFormOpen=false;resetItem()"><form class="management-dialog" data-testid="item-form" role="dialog" aria-modal="true" aria-labelledby="item-form-title" @submit.prevent="saveItem"><header class="management-dialog__header"><h2 id="item-form-title">{{itemForm.id?'修改':'新增'}}字典项</h2><button type="button" aria-label="关闭" @click="itemFormOpen=false;resetItem()">×</button></header><div class="management-dialog__body"><label>字典值<input v-model="itemForm.value" name="item-value" autofocus required></label><label>显示标签<input v-model="itemForm.label" name="item-label" required></label><label>排序<input v-model.number="itemForm.sortOrder" name="item-order" type="number" min="0" max="100000"></label><label class="choice"><input v-model="itemForm.enabled" name="item-enabled" type="checkbox">启用</label></div><footer class="management-dialog__footer"><button type="button" @click="itemFormOpen=false;resetItem()">取消</button><button data-testid="save-item" :disabled="blocked">保存</button></footer></form></div></section>
    </template>
  </section>
</template>
<style scoped>
.settings-page{display:grid;gap:16px;color:var(--ga-text-1)}header,nav,.search{display:flex;align-items:end;justify-content:space-between;gap:10px}h1,h2,p{margin:0}.workspace{display:grid;grid-template-columns:minmax(0,1fr);gap:18px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid var(--ga-border-light);text-align:left}form{display:grid;align-content:start;gap:8px}label{display:grid;gap:4px}button,input,textarea{font:inherit}[role=alert]{padding:8px;border-left:3px solid var(--ga-danger);background:#fff1f0}.items{display:grid;gap:10px;border-top:1px solid var(--ga-border-light);padding-top:14px}@media(max-width:720px){header,nav,.search{flex-wrap:wrap}}
</style>
