// Package generatortransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatortransport

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ColumnKind.
const (
	Boolean ColumnKind = "boolean"
	Bytes   ColumnKind = "bytes"
	Decimal ColumnKind = "decimal"
	Int64   ColumnKind = "int64"
	String  ColumnKind = "string"
	Time    ColumnKind = "time"
	Uuid    ColumnKind = "uuid"
)

// Valid indicates whether the value is a known member of the ColumnKind enum.
func (e ColumnKind) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Bytes:
		return true
	case Decimal:
		return true
	case Int64:
		return true
	case String:
		return true
	case Time:
		return true
	case Uuid:
		return true
	default:
		return false
	}
}

// Defines values for ConfirmedWriteConfirmed.
const (
	True ConfirmedWriteConfirmed = true
)

// Valid indicates whether the value is a known member of the ConfirmedWriteConfirmed enum.
func (e ConfirmedWriteConfirmed) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// CodeIdentifier defines model for CodeIdentifier.
type CodeIdentifier = string

// ColumnDraft defines model for ColumnDraft.
type ColumnDraft struct {
	Field      CodeIdentifier     `json:"field"`
	Include    bool               `json:"include"`
	Name       DatabaseIdentifier `json:"name"`
	Searchable bool               `json:"searchable"`
	Sortable   bool               `json:"sortable"`
}

// ColumnKind defines model for ColumnKind.
type ColumnKind string

// ColumnMetadata defines model for ColumnMetadata.
type ColumnMetadata struct {
	DatabaseType string             `json:"databaseType"`
	Kind         ColumnKind         `json:"kind"`
	Name         DatabaseIdentifier `json:"name"`
	Nullable     bool               `json:"nullable"`
	Ordinal      int                `json:"ordinal"`
	PrimaryKey   bool               `json:"primaryKey"`
}

// ConfirmedWrite defines model for ConfirmedWrite.
type ConfirmedWrite struct {
	Confirmed    ConfirmedWriteConfirmed `json:"confirmed"`
	PreviewToken string                  `json:"previewToken"`
}

// ConfirmedWriteConfirmed defines model for ConfirmedWrite.Confirmed.
type ConfirmedWriteConfirmed bool

// DatabaseIdentifier defines model for DatabaseIdentifier.
type DatabaseIdentifier = string

// GenerationDraft defines model for GenerationDraft.
type GenerationDraft struct {
	Columns []ColumnDraft    `json:"columns"`
	Entity  CodeIdentifier   `json:"entity"`
	Module  ModuleIdentifier `json:"module"`
	Plural  PathWord         `json:"plural"`
	Table   TableReference   `json:"table"`
}

// GenerationPreview defines model for GenerationPreview.
type GenerationPreview struct {
	CreatedAt time.Time        `json:"createdAt"`
	Digest    string           `json:"digest"`
	ExpiresAt time.Time        `json:"expiresAt"`
	Files     []PreviewFile    `json:"files"`
	Module    ModuleIdentifier `json:"module"`
	Token     string           `json:"token"`
}

// ModuleIdentifier defines model for ModuleIdentifier.
type ModuleIdentifier = string

// PathWord defines model for PathWord.
type PathWord = string

// PreviewFile defines model for PreviewFile.
type PreviewFile struct {
	Content string `json:"content"`
	Path    string `json:"path"`
	Sha256  string `json:"sha256"`
}

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// SavedGenerationConfig defines model for SavedGenerationConfig.
type SavedGenerationConfig struct {
	Draft         GenerationDraft `json:"draft"`
	PreviewDigest string          `json:"previewDigest"`
}

// TableMetadata defines model for TableMetadata.
type TableMetadata struct {
	Columns []ColumnMetadata `json:"columns"`
	Table   TableReference   `json:"table"`
}

// TableReference defines model for TableReference.
type TableReference struct {
	Name   DatabaseIdentifier `json:"name"`
	Schema DatabaseIdentifier `json:"schema"`
}

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// WriteResult defines model for WriteResult.
type WriteResult struct {
	Directory string   `json:"directory"`
	Files     []string `json:"files"`
	Token     string   `json:"token"`
}

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// GateProblem defines model for GateProblem.
type GateProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// PreviewGeneratorModuleJSONRequestBody defines body for PreviewGeneratorModule for application/json ContentType.
type PreviewGeneratorModuleJSONRequestBody = GenerationDraft

// WriteGeneratorModuleJSONRequestBody defines body for WriteGeneratorModule for application/json ContentType.
type WriteGeneratorModuleJSONRequestBody = ConfirmedWrite

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetGeneratorConfig Read the caller-owned persisted normalized generation config
	// (GET /generator/configs/{moduleName})
	GetGeneratorConfig(w http.ResponseWriter, r *http.Request, moduleName ModuleIdentifier)
	// PreviewGeneratorModule Produce a deterministic preview without writing files
	// (POST /generator/previews)
	PreviewGeneratorModule(w http.ResponseWriter, r *http.Request)
	// ListGeneratorTables List allowlisted tables in the current profile schema
	// (GET /generator/tables)
	ListGeneratorTables(w http.ResponseWriter, r *http.Request)
	// GetGeneratorTable Read normalized metadata for an allowlisted table
	// (GET /generator/tables/{schemaName}/{tableName})
	GetGeneratorTable(w http.ResponseWriter, r *http.Request, schemaName DatabaseIdentifier, tableName DatabaseIdentifier)
	// WriteGeneratorModule Consume an actor-bound preview token and atomically publish isolated output
	// (POST /generator/writes)
	WriteGeneratorModule(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetGeneratorConfig Read the caller-owned persisted normalized generation config
// (GET /generator/configs/{moduleName})
func (_ Unimplemented) GetGeneratorConfig(w http.ResponseWriter, r *http.Request, moduleName ModuleIdentifier) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PreviewGeneratorModule Produce a deterministic preview without writing files
// (POST /generator/previews)
func (_ Unimplemented) PreviewGeneratorModule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListGeneratorTables List allowlisted tables in the current profile schema
// (GET /generator/tables)
func (_ Unimplemented) ListGeneratorTables(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetGeneratorTable Read normalized metadata for an allowlisted table
// (GET /generator/tables/{schemaName}/{tableName})
func (_ Unimplemented) GetGeneratorTable(w http.ResponseWriter, r *http.Request, schemaName DatabaseIdentifier, tableName DatabaseIdentifier) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WriteGeneratorModule Consume an actor-bound preview token and atomically publish isolated output
// (POST /generator/writes)
func (_ Unimplemented) WriteGeneratorModule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGeneratorConfig operation middleware
func (siw *ServerInterfaceWrapper) GetGeneratorConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "moduleName" -------------
	var moduleName ModuleIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "moduleName", chi.URLParam(r, "moduleName"), &moduleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moduleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneratorConfig(w, r, moduleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewGeneratorModule operation middleware
func (siw *ServerInterfaceWrapper) PreviewGeneratorModule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewGeneratorModule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGeneratorTables operation middleware
func (siw *ServerInterfaceWrapper) ListGeneratorTables(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGeneratorTables(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneratorTable operation middleware
func (siw *ServerInterfaceWrapper) GetGeneratorTable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "schemaName" -------------
	var schemaName DatabaseIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "schemaName", chi.URLParam(r, "schemaName"), &schemaName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "schemaName", Err: err})
		return
	}

	// ------------- Path parameter "tableName" -------------
	var tableName DatabaseIdentifier

	err = runtime.BindStyledParameterWithOptions("simple", "tableName", chi.URLParam(r, "tableName"), &tableName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tableName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneratorTable(w, r, schemaName, tableName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WriteGeneratorModule operation middleware
func (siw *ServerInterfaceWrapper) WriteGeneratorModule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WriteGeneratorModule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/generator/configs/{moduleName}", wrapper.GetGeneratorConfig)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generator/previews", wrapper.PreviewGeneratorModule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/generator/tables", wrapper.ListGeneratorTables)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/generator/tables/{schemaName}/{tableName}", wrapper.GetGeneratorTable)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generator/writes", wrapper.WriteGeneratorModule)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type AuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizationProblemResponseHeaders
}

type ConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictProblemResponseHeaders
}

type GateProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type GateProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers GateProblemResponseHeaders
}

type InternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type InternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalProblemResponseHeaders
}

type NotFoundProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type NotFoundProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers NotFoundProblemResponseHeaders
}

type ValidationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ValidationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ValidationProblemResponseHeaders
}

type GetGeneratorConfigRequestObject struct {
	ModuleName ModuleIdentifier `json:"moduleName"`
}

type GetGeneratorConfigResponseObject interface {
	VisitGetGeneratorConfigResponse(w http.ResponseWriter) error
}

type GetGeneratorConfig200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetGeneratorConfig200JSONResponse struct {
	Body    SavedGenerationConfig
	Headers GetGeneratorConfig200ResponseHeaders
}

func (response GetGeneratorConfig200JSONResponse) VisitGetGeneratorConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorConfig401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorConfig401ApplicationProblemPlusJSONResponse) VisitGetGeneratorConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorConfig403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorConfig403ApplicationProblemPlusJSONResponse) VisitGetGeneratorConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorConfig404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorConfig404ApplicationProblemPlusJSONResponse) VisitGetGeneratorConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorConfig500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorConfig500ApplicationProblemPlusJSONResponse) VisitGetGeneratorConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModuleRequestObject struct {
	Body *PreviewGeneratorModuleJSONRequestBody
}

type PreviewGeneratorModuleResponseObject interface {
	VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error
}

type PreviewGeneratorModule200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type PreviewGeneratorModule200JSONResponse struct {
	Body    GenerationPreview
	Headers PreviewGeneratorModule200ResponseHeaders
}

func (response PreviewGeneratorModule200JSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModule400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response PreviewGeneratorModule400ApplicationProblemPlusJSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModule401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response PreviewGeneratorModule401ApplicationProblemPlusJSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModule403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response PreviewGeneratorModule403ApplicationProblemPlusJSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModule404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response PreviewGeneratorModule404ApplicationProblemPlusJSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewGeneratorModule500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response PreviewGeneratorModule500ApplicationProblemPlusJSONResponse) VisitPreviewGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListGeneratorTablesRequestObject struct {
}

type ListGeneratorTablesResponseObject interface {
	VisitListGeneratorTablesResponse(w http.ResponseWriter) error
}

type ListGeneratorTables200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type ListGeneratorTables200JSONResponse struct {
	Body    []TableReference
	Headers ListGeneratorTables200ResponseHeaders
}

func (response ListGeneratorTables200JSONResponse) VisitListGeneratorTablesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGeneratorTables401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListGeneratorTables401ApplicationProblemPlusJSONResponse) VisitListGeneratorTablesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListGeneratorTables403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListGeneratorTables403ApplicationProblemPlusJSONResponse) VisitListGeneratorTablesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListGeneratorTables500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListGeneratorTables500ApplicationProblemPlusJSONResponse) VisitListGeneratorTablesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorTableRequestObject struct {
	SchemaName DatabaseIdentifier `json:"schemaName"`
	TableName  DatabaseIdentifier `json:"tableName"`
}

type GetGeneratorTableResponseObject interface {
	VisitGetGeneratorTableResponse(w http.ResponseWriter) error
}

type GetGeneratorTable200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetGeneratorTable200JSONResponse struct {
	Body    TableMetadata
	Headers GetGeneratorTable200ResponseHeaders
}

func (response GetGeneratorTable200JSONResponse) VisitGetGeneratorTableResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorTable401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorTable401ApplicationProblemPlusJSONResponse) VisitGetGeneratorTableResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorTable403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorTable403ApplicationProblemPlusJSONResponse) VisitGetGeneratorTableResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorTable404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorTable404ApplicationProblemPlusJSONResponse) VisitGetGeneratorTableResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneratorTable500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetGeneratorTable500ApplicationProblemPlusJSONResponse) VisitGetGeneratorTableResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModuleRequestObject struct {
	Body *WriteGeneratorModuleJSONRequestBody
}

type WriteGeneratorModuleResponseObject interface {
	VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error
}

type WriteGeneratorModule201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type WriteGeneratorModule201JSONResponse struct {
	Body    WriteResult
	Headers WriteGeneratorModule201ResponseHeaders
}

func (response WriteGeneratorModule201JSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule400ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule401ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule403ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule409ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule422ApplicationProblemPlusJSONResponse struct {
	GateProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule422ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type WriteGeneratorModule500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response WriteGeneratorModule500ApplicationProblemPlusJSONResponse) VisitWriteGeneratorModuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetGeneratorConfig Read the caller-owned persisted normalized generation config
	// (GET /generator/configs/{moduleName})
	GetGeneratorConfig(ctx context.Context, request GetGeneratorConfigRequestObject) (GetGeneratorConfigResponseObject, error)
	// PreviewGeneratorModule Produce a deterministic preview without writing files
	// (POST /generator/previews)
	PreviewGeneratorModule(ctx context.Context, request PreviewGeneratorModuleRequestObject) (PreviewGeneratorModuleResponseObject, error)
	// ListGeneratorTables List allowlisted tables in the current profile schema
	// (GET /generator/tables)
	ListGeneratorTables(ctx context.Context, request ListGeneratorTablesRequestObject) (ListGeneratorTablesResponseObject, error)
	// GetGeneratorTable Read normalized metadata for an allowlisted table
	// (GET /generator/tables/{schemaName}/{tableName})
	GetGeneratorTable(ctx context.Context, request GetGeneratorTableRequestObject) (GetGeneratorTableResponseObject, error)
	// WriteGeneratorModule Consume an actor-bound preview token and atomically publish isolated output
	// (POST /generator/writes)
	WriteGeneratorModule(ctx context.Context, request WriteGeneratorModuleRequestObject) (WriteGeneratorModuleResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetGeneratorConfig operation middleware
func (sh *strictHandler) GetGeneratorConfig(w http.ResponseWriter, r *http.Request, moduleName ModuleIdentifier) {
	var request GetGeneratorConfigRequestObject

	request.ModuleName = moduleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGeneratorConfig(ctx, request.(GetGeneratorConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGeneratorConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGeneratorConfigResponseObject); ok {
		if err := validResponse.VisitGetGeneratorConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewGeneratorModule operation middleware
func (sh *strictHandler) PreviewGeneratorModule(w http.ResponseWriter, r *http.Request) {
	var request PreviewGeneratorModuleRequestObject

	var body PreviewGeneratorModuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewGeneratorModule(ctx, request.(PreviewGeneratorModuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewGeneratorModule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewGeneratorModuleResponseObject); ok {
		if err := validResponse.VisitPreviewGeneratorModuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGeneratorTables operation middleware
func (sh *strictHandler) ListGeneratorTables(w http.ResponseWriter, r *http.Request) {
	var request ListGeneratorTablesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGeneratorTables(ctx, request.(ListGeneratorTablesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGeneratorTables")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGeneratorTablesResponseObject); ok {
		if err := validResponse.VisitListGeneratorTablesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGeneratorTable operation middleware
func (sh *strictHandler) GetGeneratorTable(w http.ResponseWriter, r *http.Request, schemaName DatabaseIdentifier, tableName DatabaseIdentifier) {
	var request GetGeneratorTableRequestObject

	request.SchemaName = schemaName
	request.TableName = tableName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGeneratorTable(ctx, request.(GetGeneratorTableRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGeneratorTable")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGeneratorTableResponseObject); ok {
		if err := validResponse.VisitGetGeneratorTableResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WriteGeneratorModule operation middleware
func (sh *strictHandler) WriteGeneratorModule(w http.ResponseWriter, r *http.Request) {
	var request WriteGeneratorModuleRequestObject

	var body WriteGeneratorModuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WriteGeneratorModule(ctx, request.(WriteGeneratorModuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WriteGeneratorModule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WriteGeneratorModuleResponseObject); ok {
		if err := validResponse.VisitWriteGeneratorModuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
