import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { discoverModuleContracts, resolveModuleMetadata } from './modules.mjs'
import { validatePolicy } from './policy.mjs'

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const uiRoot = join(repositoryRoot, 'go-admin-ui-plus')
const canonicalContract = join(repositoryRoot, 'contracts', 'openapi', 'openapi.yaml')
const config = join(repositoryRoot, 'scripts', 'contracts', 'redocly.yaml')
const goConfigPath = join(repositoryRoot, 'scripts', 'contracts', 'oapi-codegen.yaml')
const pnpm = process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm'
const canonicalGeneratedFiles = [
  join('scripts', 'contracts', 'generated', 'openapi.json'),
  join('go-admin-plus', 'internal', 'contracts', 'openapi.gen.go'),
  join('go-admin-ui-plus', 'packages', 'api-client', 'src', 'generated', 'schema.ts'),
  join('go-admin-ui-plus', 'packages', 'api-client', 'src', 'generated', 'client.ts')
]

const fail = message => {
  console.error(`contract: ${message}`)
  process.exit(1)
}

const run = (command, args, options = {}) => {
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? repositoryRoot,
    encoding: 'utf8',
    stdio: options.capture ? 'pipe' : 'inherit'
  })
  if (result.error) fail(`${command} is required: ${result.error.message}`)
  if (result.status !== 0) process.exit(result.status ?? 1)
  return result.stdout ?? ''
}

const redocly = (...args) => run(pnpm, [
  '--dir', uiRoot,
  '--filter', '@go-admin/api-client',
  'exec', 'redocly',
  ...args
])

const optionValue = name => {
  const index = process.argv.indexOf(name)
  if (index < 0) return undefined
  if (!process.argv[index + 1]) fail(`${name} requires a value`)
  return process.argv[index + 1]
}

const bundle = (input, output, { dereferenced = false } = {}) => {
  const args = ['bundle', input]
  if (dereferenced) args.push('--dereferenced')
  redocly(...args, '--ext', 'json', '--output', output, '--config', config)
}

const lintOne = input => {
  redocly('lint', input, '--config', config)
  const temporaryDirectory = mkdtempSync(join(tmpdir(), 'go-admin-contract-'))
  const output = join(temporaryDirectory, 'bundle.json')
  try {
    bundle(input, output, { dereferenced: true })
    validatePolicy(JSON.parse(readFileSync(output, 'utf8')), {
      canonical: resolve(input) === resolve(canonicalContract)
    })
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error))
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true })
  }
}

const lintAll = () => {
  lintOne(canonicalContract)
  for (const moduleContract of discoverModuleContracts(repositoryRoot)) lintOne(moduleContract)
}

const generatedClient = `// Code generated by scripts/contracts/cli.mjs. DO NOT EDIT.\nimport createClient, { type ClientOptions } from 'openapi-fetch'\nimport type { paths } from './schema'\n\nexport const createContractClient = (options: ClientOptions) => createClient<paths>(options)\nexport type ContractClient = ReturnType<typeof createContractClient>\nexport type { components, operations, paths } from './schema'\n`

const generateGo = (input, output, packageName) => {
  const goConfig = JSON.parse(readFileSync(goConfigPath, 'utf8'))
  goConfig.package = packageName
  goConfig.output = output
  const configDirectory = mkdtempSync(join(tmpdir(), 'go-admin-oapi-config-'))
  try {
    const temporaryConfig = join(configDirectory, 'oapi-codegen.json')
    writeFileSync(temporaryConfig, `${JSON.stringify(goConfig, null, 2)}\n`)
    run('go', ['tool', 'oapi-codegen', '--config', temporaryConfig, input], {
      cwd: join(repositoryRoot, 'go-admin-plus')
    })
  } finally {
    rmSync(configDirectory, { recursive: true, force: true })
  }
}

const generateTypescript = (input, schemaOutput, clientOutput) => {
  run(pnpm, [
    '--dir', uiRoot,
    '--filter', '@go-admin/api-client',
    'exec', 'openapi-typescript', input,
    '--output', schemaOutput,
    '--alphabetize'
  ])
  writeFileSync(clientOutput, generatedClient)
}

const outputAt = (outputRoot, path) => {
  const output = join(outputRoot, path)
  mkdirSync(dirname(output), { recursive: true })
  return output
}

export const generate = (outputRoot, moduleContracts = discoverModuleContracts(repositoryRoot)) => {
  const generatedFiles = [...canonicalGeneratedFiles]
  const canonicalOutputs = Object.fromEntries(
    canonicalGeneratedFiles.map(path => [path, outputAt(outputRoot, path)])
  )
  bundle(canonicalContract, canonicalOutputs[canonicalGeneratedFiles[0]])
  generateGo(
    canonicalOutputs[canonicalGeneratedFiles[0]],
    canonicalOutputs[canonicalGeneratedFiles[1]],
    'contracts'
  )
  generateTypescript(
    canonicalOutputs[canonicalGeneratedFiles[0]],
    canonicalOutputs[canonicalGeneratedFiles[2]],
    canonicalOutputs[canonicalGeneratedFiles[3]]
  )

  const stagingDirectory = mkdtempSync(join(tmpdir(), 'go-admin-module-contracts-'))
  const moduleIds = new Set()
  const moduleOutputs = new Set()
  try {
    for (const moduleContract of moduleContracts) {
      const moduleBundle = join(stagingDirectory, `${basename(moduleContract).replace(/\.[^.]+$/, '')}.json`)
      bundle(moduleContract, moduleBundle)
      const metadata = resolveModuleMetadata(
        repositoryRoot,
        JSON.parse(readFileSync(moduleBundle, 'utf8')),
        relative(repositoryRoot, moduleContract)
      )
      if (moduleIds.has(metadata.id)) fail(`duplicate module id ${metadata.id}`)
      moduleIds.add(metadata.id)

      const relativeGoOutput = relative(repositoryRoot, metadata.goOutput)
      const relativeTypescriptDirectory = relative(repositoryRoot, metadata.typescriptOutput)
      const outputs = [
        relativeGoOutput,
        join(relativeTypescriptDirectory, 'schema.ts'),
        join(relativeTypescriptDirectory, 'client.ts')
      ]
      for (const output of outputs) {
        if (moduleOutputs.has(output) || canonicalGeneratedFiles.includes(output)) {
          fail(`multiple contracts generate ${output}`)
        }
        moduleOutputs.add(output)
        generatedFiles.push(output)
      }

      const goOutput = outputAt(outputRoot, outputs[0])
      const schemaOutput = outputAt(outputRoot, outputs[1])
      const clientOutput = outputAt(outputRoot, outputs[2])
      generateGo(moduleBundle, goOutput, metadata.goPackage)
      generateTypescript(moduleBundle, schemaOutput, clientOutput)
    }
  } finally {
    rmSync(stagingDirectory, { recursive: true, force: true })
  }
  return generatedFiles
}

const checkGeneration = () => {
  const temporaryDirectory = mkdtempSync(join(tmpdir(), 'go-admin-generate-'))
  try {
    const generatedFiles = generate(temporaryDirectory)
    const drift = generatedFiles.filter(path => {
      const expected = join(repositoryRoot, path)
      const actual = join(temporaryDirectory, path)
      return !existsSync(expected) || readFileSync(expected).compare(readFileSync(actual)) !== 0
    })
    if (drift.length) fail(`generated transport drift:\n- ${drift.join('\n- ')}`)
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true })
  }
}

const main = () => {
  const command = process.argv[2]
  switch (command) {
    case 'lint': {
      const input = optionValue('--contract')
      if (input) lintOne(resolve(repositoryRoot, input))
      else lintAll()
      console.log('CONTRACT_LINT_PASS')
      break
    }
    case 'generate':
      lintAll()
      if (process.argv.includes('--check')) {
        checkGeneration()
        console.log('CONTRACT_GENERATE_CHECK_PASS')
      } else {
        generate(repositoryRoot)
        console.log('CONTRACT_GENERATE_PASS')
      }
      break
    default:
      fail(`unknown command ${JSON.stringify(command)}`)
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
