// Package demotransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package demotransport

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// Defines values for ProductSort.
const (
	Name       ProductSort = "name"
	PriceCents ProductSort = "priceCents"
	Sku        ProductSort = "sku"
	UpdatedAt  ProductSort = "updatedAt"
)

// Valid indicates whether the value is a known member of the ProductSort enum.
func (e ProductSort) Valid() bool {
	switch e {
	case Name:
		return true
	case PriceCents:
		return true
	case Sku:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ProductStatus.
const (
	Active   ProductStatus = "active"
	Inactive ProductStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ProductStatus enum.
func (e ProductStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// Defines values for SortDirection.
const (
	Ascending  SortDirection = "ascending"
	Descending SortDirection = "descending"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
	switch e {
	case Ascending:
		return true
	case Descending:
		return true
	default:
		return false
	}
}

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest = ProductInput

// DeleteProductTarget defines model for DeleteProductTarget.
type DeleteProductTarget struct {
	Id       openapi_types.UUID `json:"id"`
	Revision int                `json:"revision"`
}

// DeleteProductsRequest defines model for DeleteProductsRequest.
type DeleteProductsRequest struct {
	Products []DeleteProductTarget `json:"products"`
}

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// Product defines model for Product.
type Product struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	PriceCents  int                `json:"priceCents"`
	Revision    int                `json:"revision"`
	Sku         string             `json:"sku"`
	Status      ProductStatus      `json:"status"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// ProductInput defines model for ProductInput.
type ProductInput struct {
	Description string        `json:"description"`
	Name        string        `json:"name"`
	PriceCents  int           `json:"priceCents"`
	Sku         string        `json:"sku"`
	Status      ProductStatus `json:"status"`
}

// ProductPage defines model for ProductPage.
type ProductPage struct {
	Rows  []Product `json:"rows"`
	Total int       `json:"total"`
}

// ProductSort defines model for ProductSort.
type ProductSort string

// ProductStatus defines model for ProductStatus.
type ProductStatus string

// SortDirection defines model for SortDirection.
type SortDirection string

// UpdateProductRequest defines model for UpdateProductRequest.
type UpdateProductRequest struct {
	Description string        `json:"description"`
	Name        string        `json:"name"`
	PriceCents  int           `json:"priceCents"`
	Revision    int           `json:"revision"`
	Sku         string        `json:"sku"`
	Status      ProductStatus `json:"status"`
}

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ListDemoProductsParams defines parameters for ListDemoProducts.
type ListDemoProductsParams struct {
	Search    *string        `form:"search,omitempty" json:"search,omitempty"`
	Page      *int           `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Sort      *ProductSort   `form:"sort,omitempty" json:"sort,omitempty"`
	Direction *SortDirection `form:"direction,omitempty" json:"direction,omitempty"`
}

// CreateDemoProductJSONRequestBody defines body for CreateDemoProduct for application/json ContentType.
type CreateDemoProductJSONRequestBody = CreateProductRequest

// DeleteDemoProductsJSONRequestBody defines body for DeleteDemoProducts for application/json ContentType.
type DeleteDemoProductsJSONRequestBody = DeleteProductsRequest

// UpdateDemoProductJSONRequestBody defines body for UpdateDemoProduct for application/json ContentType.
type UpdateDemoProductJSONRequestBody = UpdateProductRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDemoProducts List products within the caller data scope
	// (GET /demo/products)
	ListDemoProducts(w http.ResponseWriter, r *http.Request, params ListDemoProductsParams)
	// CreateDemoProduct Create a product
	// (POST /demo/products)
	CreateDemoProduct(w http.ResponseWriter, r *http.Request)
	// DeleteDemoProducts Delete products atomically
	// (POST /demo/products/batch-delete)
	DeleteDemoProducts(w http.ResponseWriter, r *http.Request)
	// GetDemoProduct Get a product within the caller data scope
	// (GET /demo/products/{productId})
	GetDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// UpdateDemoProduct Update a product with optimistic concurrency
	// (PATCH /demo/products/{productId})
	UpdateDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListDemoProducts List products within the caller data scope
// (GET /demo/products)
func (_ Unimplemented) ListDemoProducts(w http.ResponseWriter, r *http.Request, params ListDemoProductsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateDemoProduct Create a product
// (POST /demo/products)
func (_ Unimplemented) CreateDemoProduct(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteDemoProducts Delete products atomically
// (POST /demo/products/batch-delete)
func (_ Unimplemented) DeleteDemoProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDemoProduct Get a product within the caller data scope
// (GET /demo/products/{productId})
func (_ Unimplemented) GetDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateDemoProduct Update a product with optimistic concurrency
// (PATCH /demo/products/{productId})
func (_ Unimplemented) UpdateDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDemoProducts operation middleware
func (siw *ServerInterfaceWrapper) ListDemoProducts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDemoProductsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", r.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "direction"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDemoProducts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDemoProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateDemoProduct(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDemoProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDemoProducts operation middleware
func (siw *ServerInterfaceWrapper) DeleteDemoProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDemoProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDemoProduct operation middleware
func (siw *ServerInterfaceWrapper) GetDemoProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDemoProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDemoProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateDemoProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDemoProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/demo/products", wrapper.ListDemoProducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/demo/products", wrapper.CreateDemoProduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/demo/products/batch-delete", wrapper.DeleteDemoProducts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/demo/products/{productId}", wrapper.GetDemoProduct)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/demo/products/{productId}", wrapper.UpdateDemoProduct)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type AuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizationProblemResponseHeaders
}

type ConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictProblemResponseHeaders
}

type InternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type InternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalProblemResponseHeaders
}

type NotFoundProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type NotFoundProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers NotFoundProblemResponseHeaders
}

type ValidationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}
type ValidationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ValidationProblemResponseHeaders
}

type ListDemoProductsRequestObject struct {
	Params ListDemoProductsParams
}

type ListDemoProductsResponseObject interface {
	VisitListDemoProductsResponse(w http.ResponseWriter) error
}

type ListDemoProducts200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type ListDemoProducts200JSONResponse struct {
	Body    ProductPage
	Headers ListDemoProducts200ResponseHeaders
}

func (response ListDemoProducts200JSONResponse) VisitListDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDemoProducts400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListDemoProducts400ApplicationProblemPlusJSONResponse) VisitListDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDemoProducts401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListDemoProducts401ApplicationProblemPlusJSONResponse) VisitListDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDemoProducts403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListDemoProducts403ApplicationProblemPlusJSONResponse) VisitListDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListDemoProducts500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListDemoProducts500ApplicationProblemPlusJSONResponse) VisitListDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProductRequestObject struct {
	Body *CreateDemoProductJSONRequestBody
}

type CreateDemoProductResponseObject interface {
	VisitCreateDemoProductResponse(w http.ResponseWriter) error
}

type CreateDemoProduct201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type CreateDemoProduct201JSONResponse struct {
	Body    Product
	Headers CreateDemoProduct201ResponseHeaders
}

func (response CreateDemoProduct201JSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProduct400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response CreateDemoProduct400ApplicationProblemPlusJSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProduct401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response CreateDemoProduct401ApplicationProblemPlusJSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProduct403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response CreateDemoProduct403ApplicationProblemPlusJSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProduct409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response CreateDemoProduct409ApplicationProblemPlusJSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDemoProduct500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response CreateDemoProduct500ApplicationProblemPlusJSONResponse) VisitCreateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProductsRequestObject struct {
	Body *DeleteDemoProductsJSONRequestBody
}

type DeleteDemoProductsResponseObject interface {
	VisitDeleteDemoProductsResponse(w http.ResponseWriter) error
}

type DeleteDemoProducts204ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type DeleteDemoProducts204Response struct {
	Headers DeleteDemoProducts204ResponseHeaders
}

func (response DeleteDemoProducts204Response) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(204)
	return nil
}

type DeleteDemoProducts400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts400ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProducts401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts401ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProducts403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts403ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProducts404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts404ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProducts409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts409ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDemoProducts500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DeleteDemoProducts500ApplicationProblemPlusJSONResponse) VisitDeleteDemoProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetDemoProductRequestObject struct {
	ProductId ProductId `json:"productId"`
}

type GetDemoProductResponseObject interface {
	VisitGetDemoProductResponse(w http.ResponseWriter) error
}

type GetDemoProduct200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type GetDemoProduct200JSONResponse struct {
	Body    Product
	Headers GetDemoProduct200ResponseHeaders
}

func (response GetDemoProduct200JSONResponse) VisitGetDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDemoProduct401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response GetDemoProduct401ApplicationProblemPlusJSONResponse) VisitGetDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDemoProduct403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response GetDemoProduct403ApplicationProblemPlusJSONResponse) VisitGetDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetDemoProduct404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response GetDemoProduct404ApplicationProblemPlusJSONResponse) VisitGetDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDemoProduct500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response GetDemoProduct500ApplicationProblemPlusJSONResponse) VisitGetDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProductRequestObject struct {
	ProductId ProductId `json:"productId"`
	Body      *UpdateDemoProductJSONRequestBody
}

type UpdateDemoProductResponseObject interface {
	VisitUpdateDemoProductResponse(w http.ResponseWriter) error
}

type UpdateDemoProduct200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken string
}

type UpdateDemoProduct200JSONResponse struct {
	Body    Product
	Headers UpdateDemoProduct200ResponseHeaders
}

func (response UpdateDemoProduct200JSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct400ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct401ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct403ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct404ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct409ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDemoProduct500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UpdateDemoProduct500ApplicationProblemPlusJSONResponse) VisitUpdateDemoProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.Header().Set("X-CSRF-Token", fmt.Sprint(response.Headers.XCSRFToken))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListDemoProducts List products within the caller data scope
	// (GET /demo/products)
	ListDemoProducts(ctx context.Context, request ListDemoProductsRequestObject) (ListDemoProductsResponseObject, error)
	// CreateDemoProduct Create a product
	// (POST /demo/products)
	CreateDemoProduct(ctx context.Context, request CreateDemoProductRequestObject) (CreateDemoProductResponseObject, error)
	// DeleteDemoProducts Delete products atomically
	// (POST /demo/products/batch-delete)
	DeleteDemoProducts(ctx context.Context, request DeleteDemoProductsRequestObject) (DeleteDemoProductsResponseObject, error)
	// GetDemoProduct Get a product within the caller data scope
	// (GET /demo/products/{productId})
	GetDemoProduct(ctx context.Context, request GetDemoProductRequestObject) (GetDemoProductResponseObject, error)
	// UpdateDemoProduct Update a product with optimistic concurrency
	// (PATCH /demo/products/{productId})
	UpdateDemoProduct(ctx context.Context, request UpdateDemoProductRequestObject) (UpdateDemoProductResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDemoProducts operation middleware
func (sh *strictHandler) ListDemoProducts(w http.ResponseWriter, r *http.Request, params ListDemoProductsParams) {
	var request ListDemoProductsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDemoProducts(ctx, request.(ListDemoProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDemoProducts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDemoProductsResponseObject); ok {
		if err := validResponse.VisitListDemoProductsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDemoProduct operation middleware
func (sh *strictHandler) CreateDemoProduct(w http.ResponseWriter, r *http.Request) {
	var request CreateDemoProductRequestObject

	var body CreateDemoProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDemoProduct(ctx, request.(CreateDemoProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDemoProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDemoProductResponseObject); ok {
		if err := validResponse.VisitCreateDemoProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDemoProducts operation middleware
func (sh *strictHandler) DeleteDemoProducts(w http.ResponseWriter, r *http.Request) {
	var request DeleteDemoProductsRequestObject

	var body DeleteDemoProductsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDemoProducts(ctx, request.(DeleteDemoProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDemoProducts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDemoProductsResponseObject); ok {
		if err := validResponse.VisitDeleteDemoProductsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDemoProduct operation middleware
func (sh *strictHandler) GetDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request GetDemoProductRequestObject

	request.ProductId = productId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDemoProduct(ctx, request.(GetDemoProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDemoProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDemoProductResponseObject); ok {
		if err := validResponse.VisitGetDemoProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDemoProduct operation middleware
func (sh *strictHandler) UpdateDemoProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request UpdateDemoProductRequestObject

	request.ProductId = productId

	var body UpdateDemoProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDemoProduct(ctx, request.(UpdateDemoProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDemoProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDemoProductResponseObject); ok {
		if err := validResponse.VisitUpdateDemoProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
