services:
  api-postgres:
    command:
      - --profile=server-postgres
      - --config=/run/config/server-postgres.json
      - --data-root=/var/lib/go-admin-plus
      - --repository-root=/missing-release-skeleton
  api-sqlite:
    command:
      - --profile=server-sqlite
      - --config=/run/config/server-sqlite.json
      - --data-root=/var/lib/go-admin-plus
      - --repository-root=/missing-release-skeleton
