x-server-build: &server-build
  context: ../..
  dockerfile: release/linux/Containerfile.server
  args:
    VERSION: ${GO_ADMIN_RELEASE_VERSION:-0.0.0-dev}
    VCS_REF: ${GO_ADMIN_SOURCE_SHA:-unknown}

x-web-build: &web-build
  context: ../..
  dockerfile: release/linux/Containerfile.web
  args:
    VERSION: ${GO_ADMIN_RELEASE_VERSION:-0.0.0-dev}
    VCS_REF: ${GO_ADMIN_SOURCE_SHA:-unknown}

services:
  api-postgres:
    build: *server-build
  api-sqlite:
    build: *server-build
  web-postgres:
    build: *web-build
  web-sqlite:
    build: *web-build
