services:
  migrate:
    build:
      context: ../../go-admin-plus
      dockerfile: Dockerfile
      args:
        VERSION: ${GO_ADMIN_VERSION:-dev}
        VCS_REF: ${GO_ADMIN_BACKEND_SHA:-unknown}
      platforms:
        - linux/amd64

  api:
    build:
      context: ../../go-admin-plus
      dockerfile: Dockerfile
      args:
        VERSION: ${GO_ADMIN_VERSION:-dev}
        VCS_REF: ${GO_ADMIN_BACKEND_SHA:-unknown}
      platforms:
        - linux/amd64

  web:
    build:
      context: ../../go-admin-ui-plus
      dockerfile: Dockerfile
      args:
        VERSION: ${GO_ADMIN_VERSION:-dev}
        VCS_REF: ${GO_ADMIN_FRONTEND_SHA:-unknown}
      platforms:
        - linux/amd64
