settings:
  application:
    mode: prod
    host: 0.0.0.0
    name: go-admin-plus
    port: 8000
    readtimeout: 30
    writetimeout: 30
    enabledp: true
  logger:
    path: /tmp/go-admin/logs
    stdout: default
    level: info
    enableddb: false
  jwt:
    secret: __JWT_SECRET__
    timeout: 3600
  database:
    driver: postgres
    source: host=postgres port=5432 user=go_admin password=__POSTGRES_PASSWORD__ dbname=go_admin sslmode=disable TimeZone=UTC
  cache:
    redis:
      url: redis://redis:6379/0
  queue:
    redis:
      url: redis://redis:6379/0
      group: go-admin
      key_prefix: go-admin
      max_attempts: 5
