// Code generated from go-admin-plus/api/openapi/openapi.json. DO NOT EDIT.

export interface components {
  readonly schemas: {
    readonly "ApiErrorEnvelope": { readonly "code": number; readonly "data"?: unknown | null; readonly "msg": string }
    readonly "OperationalStatus": { readonly "status": "live" | "ready" | "not_ready" | "method_not_allowed" }
    readonly "RuntimeCapabilities": { readonly "desktop": boolean; readonly "hostProfile": string; readonly "nativeDialogs": boolean; readonly "offline": boolean; readonly "version": string }
    readonly "dto.GetSetSysConfigReq": { readonly "configKey"?: string; readonly "configValue"?: string }
    readonly "dto.PassWord": { readonly "newPassword"?: string; readonly "oldPassword"?: string }
    readonly "dto.ResetSysUserPwdReq": { readonly "createBy"?: number; readonly "password"?: string; readonly "updateBy"?: number; readonly "userId"?: number }
    readonly "dto.RoleDataScopeReq": { readonly "dataScope": string; readonly "deptIds"?: ReadonlyArray<number>; readonly "roleId": number }
    readonly "dto.SysApiDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysApiUpdateReq": { readonly "action"?: string; readonly "createBy"?: number; readonly "handle"?: string; readonly "id"?: number; readonly "path"?: string; readonly "title"?: string; readonly "type"?: string; readonly "updateBy"?: number }
    readonly "dto.SysConfigByKeyReq": { readonly "configKey"?: string }
    readonly "dto.SysConfigControl": { readonly "configKey"?: string; readonly "configName"?: string; readonly "configType"?: string; readonly "configValue"?: string; readonly "createBy"?: number; readonly "id"?: number; readonly "isFrontend"?: string; readonly "remark"?: string; readonly "updateBy"?: number }
    readonly "dto.SysDeptDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysDeptInsertReq": { readonly "createBy"?: number; readonly "deptId"?: number; readonly "deptName"?: string; readonly "deptPath"?: string; readonly "email"?: string; readonly "leader"?: string; readonly "parentId"?: number; readonly "phone"?: string; readonly "sort"?: number; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysDeptUpdateReq": { readonly "createBy"?: number; readonly "deptId"?: number; readonly "deptName"?: string; readonly "deptPath"?: string; readonly "email"?: string; readonly "leader"?: string; readonly "parentId"?: number; readonly "phone"?: string; readonly "sort"?: number; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysDictDataDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysDictDataGetAllResp": { readonly "label"?: string; readonly "value"?: string }
    readonly "dto.SysDictDataInsertReq": { readonly "createBy"?: number; readonly "cssClass"?: string; readonly "default"?: string; readonly "dictLabel"?: string; readonly "dictSort"?: number; readonly "dictType"?: string; readonly "dictValue"?: string; readonly "isDefault"?: string; readonly "listClass"?: string; readonly "remark"?: string; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysDictDataUpdateReq": { readonly "createBy"?: number; readonly "cssClass"?: string; readonly "default"?: string; readonly "dictLabel"?: string; readonly "dictSort"?: number; readonly "dictType"?: string; readonly "dictValue"?: string; readonly "id"?: number; readonly "isDefault"?: string; readonly "listClass"?: string; readonly "remark"?: string; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysDictTypeDeleteReq": { readonly "createBy"?: number; readonly "ids"?: ReadonlyArray<number>; readonly "updateBy"?: number }
    readonly "dto.SysDictTypeInsertReq": { readonly "createBy"?: number; readonly "dictName"?: string; readonly "dictType"?: string; readonly "id"?: number; readonly "remark"?: string; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysDictTypeUpdateReq": { readonly "createBy"?: number; readonly "dictName"?: string; readonly "dictType"?: string; readonly "id"?: number; readonly "remark"?: string; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysLoginLogDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysMenuDeleteReq": { readonly "createBy"?: number; readonly "ids"?: ReadonlyArray<number>; readonly "updateBy"?: number }
    readonly "dto.SysMenuInsertReq": { readonly "action"?: string; readonly "apis"?: ReadonlyArray<number>; readonly "breadcrumb"?: string; readonly "component"?: string; readonly "createBy"?: number; readonly "icon"?: string; readonly "isFrame"?: string; readonly "menuId"?: number; readonly "menuName"?: string; readonly "menuType"?: string; readonly "noCache"?: boolean; readonly "parentId"?: number; readonly "path"?: string; readonly "paths"?: string; readonly "permission"?: string; readonly "sort"?: number; readonly "sysApi"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysApi"]>; readonly "title"?: string; readonly "updateBy"?: number; readonly "visible"?: string }
    readonly "dto.SysMenuUpdateReq": { readonly "action"?: string; readonly "apis"?: ReadonlyArray<number>; readonly "breadcrumb"?: string; readonly "component"?: string; readonly "createBy"?: number; readonly "icon"?: string; readonly "isFrame"?: string; readonly "menuId"?: number; readonly "menuName"?: string; readonly "menuType"?: string; readonly "noCache"?: boolean; readonly "parentId"?: number; readonly "path"?: string; readonly "paths"?: string; readonly "permission"?: string; readonly "sort"?: number; readonly "sysApi"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysApi"]>; readonly "title"?: string; readonly "updateBy"?: number; readonly "visible"?: string }
    readonly "dto.SysOperaLogDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysPostDeleteReq": { readonly "createBy"?: number; readonly "ids"?: ReadonlyArray<number>; readonly "updateBy"?: number }
    readonly "dto.SysPostInsertReq": { readonly "createBy"?: number; readonly "postCode"?: string; readonly "postId"?: number; readonly "postName"?: string; readonly "remark"?: string; readonly "sort"?: number; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysPostUpdateReq": { readonly "createBy"?: number; readonly "postCode"?: string; readonly "postId"?: number; readonly "postName"?: string; readonly "remark"?: string; readonly "sort"?: number; readonly "status"?: number; readonly "updateBy"?: number }
    readonly "dto.SysRoleDeleteReq": { readonly "ids"?: ReadonlyArray<number> }
    readonly "dto.SysRoleInsertReq": { readonly "admin"?: boolean; readonly "createBy"?: number; readonly "dataScope"?: string; readonly "deptIds"?: ReadonlyArray<number>; readonly "flag"?: string; readonly "menuIds"?: ReadonlyArray<number>; readonly "remark"?: string; readonly "roleId"?: number; readonly "roleKey"?: string; readonly "roleName"?: string; readonly "roleSort"?: number; readonly "status"?: string; readonly "sysDept"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysDept"]>; readonly "sysMenu"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysMenu"]>; readonly "updateBy"?: number }
    readonly "dto.SysRoleUpdateReq": { readonly "admin"?: boolean; readonly "createBy"?: number; readonly "dataScope"?: string; readonly "deptIds"?: ReadonlyArray<number>; readonly "flag"?: string; readonly "menuIds"?: ReadonlyArray<number>; readonly "remark"?: string; readonly "roleId"?: number; readonly "roleKey"?: string; readonly "roleName"?: string; readonly "roleSort"?: number; readonly "status"?: string; readonly "sysDept"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysDept"]>; readonly "sysMenu"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysMenu"]>; readonly "updateBy"?: number }
    readonly "dto.SysUserInsertReq": { readonly "avatar"?: string; readonly "createBy"?: number; readonly "deptId"?: number; readonly "email"?: string; readonly "nickName"?: string; readonly "password"?: string; readonly "phone"?: string; readonly "postId"?: number; readonly "remark"?: string; readonly "roleId"?: number; readonly "sex"?: string; readonly "status"?: string; readonly "updateBy"?: number; readonly "userId"?: number; readonly "username"?: string }
    readonly "dto.SysUserUpdateReq": { readonly "avatar"?: string; readonly "createBy"?: number; readonly "deptId"?: number; readonly "email"?: string; readonly "nickName"?: string; readonly "phone"?: string; readonly "postId"?: number; readonly "remark"?: string; readonly "roleId"?: number; readonly "sex"?: string; readonly "status"?: string; readonly "updateBy"?: number; readonly "userId"?: number; readonly "username"?: string }
    readonly "dto.UpdateStatusReq": { readonly "createBy"?: number; readonly "roleId"?: number; readonly "status"?: string; readonly "updateBy"?: number }
    readonly "dto.UpdateSysUserStatusReq": { readonly "createBy"?: number; readonly "status"?: string; readonly "updateBy"?: number; readonly "userId"?: number }
    readonly "go-admin_app_admin_models.SysApi": { readonly "action"?: string; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "handle"?: string; readonly "id"?: number; readonly "path"?: string; readonly "title"?: string; readonly "type"?: string; readonly "updateBy"?: number; readonly "updatedAt"?: string }
    readonly "go-admin_app_admin_models.SysConfig": { readonly "configKey"?: string; readonly "configName"?: string; readonly "configType"?: string; readonly "configValue"?: string; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "id"?: number; readonly "isFrontend"?: string; readonly "remark"?: string; readonly "updateBy"?: number; readonly "updatedAt"?: string }
    readonly "go-admin_app_admin_models.SysDept": { readonly "children"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysDept"]>; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "dataScope"?: string; readonly "deptId"?: number; readonly "deptName"?: string; readonly "deptPath"?: string; readonly "email"?: string; readonly "leader"?: string; readonly "params"?: string; readonly "parentId"?: number; readonly "phone"?: string; readonly "sort"?: number; readonly "status"?: number; readonly "updateBy"?: number; readonly "updatedAt"?: string }
    readonly "go-admin_app_admin_models.SysMenu": { readonly "action"?: string; readonly "apis"?: ReadonlyArray<number>; readonly "breadcrumb"?: string; readonly "children"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysMenu"]>; readonly "component"?: string; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "dataScope"?: string; readonly "icon"?: string; readonly "isFrame"?: string; readonly "is_select"?: boolean; readonly "menuId"?: number; readonly "menuName"?: string; readonly "menuType"?: string; readonly "noCache"?: boolean; readonly "params"?: string; readonly "parentId"?: number; readonly "path"?: string; readonly "paths"?: string; readonly "permission"?: string; readonly "roleId"?: number; readonly "routeKey"?: string; readonly "sort"?: number; readonly "sysApi"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysApi"]>; readonly "title"?: string; readonly "updateBy"?: number; readonly "updatedAt"?: string; readonly "visible"?: string }
    readonly "handler.Login": { readonly "code": string; readonly "password": string; readonly "username": string; readonly "uuid": string }
    readonly "response.Page": { readonly "count"?: number; readonly "pageIndex"?: number; readonly "pageSize"?: number }
    readonly "response.Response": { readonly "code"?: number; readonly "msg"?: string; readonly "requestId"?: string; readonly "status"?: string }
    readonly "tools.Params": { readonly "treeCode"?: string; readonly "treeName"?: string; readonly "treeParentCode"?: string }
    readonly "tools.SysColumns": { readonly "columnComment"?: string; readonly "columnId"?: number; readonly "columnName"?: string; readonly "columnType"?: string; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "dictType"?: string; readonly "edit"?: boolean; readonly "fkCol"?: ReadonlyArray<components['schemas']["tools.SysColumns"]>; readonly "fkLabelId"?: string; readonly "fkLabelName"?: string; readonly "fkTableName"?: string; readonly "fkTableNameClass"?: string; readonly "fkTableNamePackage"?: string; readonly "goField"?: string; readonly "goType"?: string; readonly "htmlType"?: string; readonly "increment"?: boolean; readonly "insert"?: boolean; readonly "isEdit"?: string; readonly "isIncrement"?: string; readonly "isInsert"?: string; readonly "isList"?: string; readonly "isPk"?: string; readonly "isQuery"?: string; readonly "isRequired"?: string; readonly "jsonField"?: string; readonly "list"?: string; readonly "pk"?: boolean; readonly "query"?: boolean; readonly "queryType"?: string; readonly "remark"?: string; readonly "required"?: boolean; readonly "sort"?: number; readonly "superColumn"?: boolean; readonly "tableId"?: number; readonly "updateBy"?: number; readonly "updatedAt"?: string; readonly "usableColumn"?: boolean }
    readonly "tools.SysTables": { readonly "businessName"?: string; readonly "className"?: string; readonly "columns"?: ReadonlyArray<components['schemas']["tools.SysColumns"]>; readonly "createBy"?: number; readonly "createdAt"?: string; readonly "crud"?: boolean; readonly "dataScope"?: string; readonly "functionAuthor"?: string; readonly "functionName"?: string; readonly "isActions"?: number; readonly "isAuth"?: number; readonly "isDataScope"?: number; readonly "isLogicalDelete"?: string; readonly "logicalDelete"?: boolean; readonly "logicalDeleteColumn"?: string; readonly "moduleFrontName"?: string; readonly "moduleName"?: string; readonly "options"?: string; readonly "packageName"?: string; readonly "params"?: components['schemas']["tools.Params"]; readonly "pkColumn"?: string; readonly "pkGoField"?: string; readonly "pkJsonField"?: string; readonly "remark"?: string; readonly "tableComment"?: string; readonly "tableId"?: number; readonly "tableName"?: string; readonly "tplCategory"?: string; readonly "tree"?: boolean; readonly "treeCode"?: string; readonly "treeName"?: string; readonly "treeParentCode"?: string; readonly "updateBy"?: number; readonly "updatedAt"?: string }
  }
}

export interface operations {
    readonly "getApiV1AppConfig": { readonly method: "GET"; readonly path: "/api/v1/app-config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: { readonly [key: string]: string } } | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Captcha": { readonly method: "GET"; readonly path: "/api/v1/captcha"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: string; readonly "id"?: string; readonly "msg"?: string } | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1Config": { readonly method: "DELETE"; readonly path: "/api/v1/config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: ReadonlyArray<number>; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Config": { readonly method: "GET"; readonly path: "/api/v1/config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "configName"?: string; readonly "configKey"?: string; readonly "configType"?: string; readonly "isFrontend"?: number; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: components['schemas']["response.Page"] & { readonly "list"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysApi"]> } } | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Config": { readonly method: "POST"; readonly path: "/api/v1/config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysConfigControl"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1ConfigId": { readonly method: "GET"; readonly path: "/api/v1/config/{id}"; readonly pathParameters: { readonly "configKey"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: components['schemas']["dto.SysConfigByKeyReq"] } | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1ConfigId": { readonly method: "PUT"; readonly path: "/api/v1/config/{id}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysConfigControl"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getConfigByKey": { readonly method: "GET"; readonly path: "/api/v1/configKey/{configKey}"; readonly pathParameters: { readonly "configKey": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DbColumnsPage": { readonly method: "GET"; readonly path: "/api/v1/db/columns/page"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "tableName"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DbTablesPage": { readonly method: "GET"; readonly path: "/api/v1/db/tables/page"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "tableName"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteDemoProducts": { readonly method: "DELETE"; readonly path: "/api/v1/demo-product"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "listDemoProducts": { readonly method: "GET"; readonly path: "/api/v1/demo-product"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "createDemoProduct": { readonly method: "POST"; readonly path: "/api/v1/demo-product"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: { readonly [key: string]: unknown }; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getDemoProduct": { readonly method: "GET"; readonly path: "/api/v1/demo-product/{id}"; readonly pathParameters: { readonly "id": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "updateDemoProduct": { readonly method: "PUT"; readonly path: "/api/v1/demo-product/{id}"; readonly pathParameters: { readonly "id": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: { readonly [key: string]: unknown }; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1Dept": { readonly method: "DELETE"; readonly path: "/api/v1/dept"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDeptDeleteReq"]; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Dept": { readonly method: "GET"; readonly path: "/api/v1/dept"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "deptName"?: string; readonly "deptId"?: string; readonly "position"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Dept": { readonly method: "POST"; readonly path: "/api/v1/dept"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDeptInsertReq"]; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DeptId": { readonly method: "GET"; readonly path: "/api/v1/dept/{id}"; readonly pathParameters: { readonly "id"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1DeptId": { readonly method: "PUT"; readonly path: "/api/v1/dept/{id}"; readonly pathParameters: { readonly "id": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDeptUpdateReq"]; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "getDepartmentTree": { readonly method: "GET"; readonly path: "/api/v1/deptTree"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictDataOptionSelect": { readonly method: "GET"; readonly path: "/api/v1/dict-data/option-select"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "dictType": number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: ReadonlyArray<components['schemas']["dto.SysDictDataGetAllResp"]> } | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1DictData": { readonly method: "DELETE"; readonly path: "/api/v1/dict/data"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictDataDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictData": { readonly method: "GET"; readonly path: "/api/v1/dict/data"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "status"?: string; readonly "dictCode"?: string; readonly "dictType"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1DictData": { readonly method: "POST"; readonly path: "/api/v1/dict/data"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictDataInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictDataDictCode": { readonly method: "GET"; readonly path: "/api/v1/dict/data/{dictCode}"; readonly pathParameters: { readonly "dictCode": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1DictDataDictCode": { readonly method: "PUT"; readonly path: "/api/v1/dict/data/{dictCode}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictDataUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1DictType": { readonly method: "DELETE"; readonly path: "/api/v1/dict/type"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictTypeDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictType": { readonly method: "GET"; readonly path: "/api/v1/dict/type"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "dictName"?: string; readonly "dictId"?: string; readonly "dictType"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1DictType": { readonly method: "POST"; readonly path: "/api/v1/dict/type"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictTypeInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictTypeOptionSelect": { readonly method: "GET"; readonly path: "/api/v1/dict/type-option-select"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "dictName"?: string; readonly "dictId"?: string; readonly "dictType"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1DictTypeId": { readonly method: "GET"; readonly path: "/api/v1/dict/type/{id}"; readonly pathParameters: { readonly "id": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1DictTypeId": { readonly method: "PUT"; readonly path: "/api/v1/dict/type/{id}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysDictTypeUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "generateAPIFile": { readonly method: "GET"; readonly path: "/api/v1/gen/apitofile/{tableId}"; readonly pathParameters: { readonly "tableId": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "previewGeneratedCode": { readonly method: "GET"; readonly path: "/api/v1/gen/preview/{tableId}"; readonly pathParameters: { readonly "tableId": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getGeneratedTableTree": { readonly method: "GET"; readonly path: "/api/v1/gen/tabletree"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "generateMenuAndAPI": { readonly method: "GET"; readonly path: "/api/v1/gen/todb/{tableId}"; readonly pathParameters: { readonly "tableId": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "generateCodeToProject": { readonly method: "GET"; readonly path: "/api/v1/gen/toproject/{tableId}"; readonly pathParameters: { readonly "tableId": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Getinfo": { readonly method: "GET"; readonly path: "/api/v1/getinfo"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getLegacyHealth": { readonly method: "GET"; readonly path: "/api/v1/health"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: unknown }
    readonly "removeJob": { readonly method: "GET"; readonly path: "/api/v1/job/remove/{id}"; readonly pathParameters: { readonly "id": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "startJob": { readonly method: "GET"; readonly path: "/api/v1/job/start/{id}"; readonly pathParameters: { readonly "id": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Login": { readonly method: "POST"; readonly path: "/api/v1/login"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["handler.Login"]; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Logout": { readonly method: "POST"; readonly path: "/api/v1/logout"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1Menu": { readonly method: "DELETE"; readonly path: "/api/v1/menu"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysMenuDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Menu": { readonly method: "GET"; readonly path: "/api/v1/menu"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "menuName"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Menu": { readonly method: "POST"; readonly path: "/api/v1/menu"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysMenuInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1MenuId": { readonly method: "GET"; readonly path: "/api/v1/menu/{id}"; readonly pathParameters: { readonly "id"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1MenuId": { readonly method: "PUT"; readonly path: "/api/v1/menu/{id}"; readonly pathParameters: { readonly "id": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysMenuUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Menurole": { readonly method: "GET"; readonly path: "/api/v1/menurole"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getMetrics": { readonly method: "GET"; readonly path: "/api/v1/metrics"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: unknown }
    readonly "deleteApiV1Post": { readonly method: "DELETE"; readonly path: "/api/v1/post"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysPostDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Post": { readonly method: "GET"; readonly path: "/api/v1/post"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "postName"?: string; readonly "postCode"?: string; readonly "postId"?: string; readonly "status"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Post": { readonly method: "POST"; readonly path: "/api/v1/post"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysPostInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1PostId": { readonly method: "GET"; readonly path: "/api/v1/post/{id}"; readonly pathParameters: { readonly "id": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1PostId": { readonly method: "PUT"; readonly path: "/api/v1/post/{id}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysPostUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1PublicUploadFile": { readonly method: "POST"; readonly path: "/api/v1/public/uploadFile"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "type": string }; readonly requestBody: unknown; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1Role": { readonly method: "DELETE"; readonly path: "/api/v1/role"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysRoleDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1Role": { readonly method: "GET"; readonly path: "/api/v1/role"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "roleName"?: string; readonly "status"?: string; readonly "roleKey"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1Role": { readonly method: "POST"; readonly path: "/api/v1/role"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysRoleInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1RoleStatus": { readonly method: "PUT"; readonly path: "/api/v1/role-status"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.RoleDataScopeReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1RoleId": { readonly method: "GET"; readonly path: "/api/v1/role/{id}"; readonly pathParameters: { readonly "roleId"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1RoleId": { readonly method: "PUT"; readonly path: "/api/v1/role/{id}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysRoleUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getRoleDepartmentTree": { readonly method: "GET"; readonly path: "/api/v1/roleDeptTreeselect/{roleId}"; readonly pathParameters: { readonly "roleId": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1RoleMenuTreeselectRoleId": { readonly method: "GET"; readonly path: "/api/v1/roleMenuTreeselect/{roleId}"; readonly pathParameters: { readonly "roleId": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "updateRoleDataScope": { readonly method: "PUT"; readonly path: "/api/v1/roledatascope"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: { readonly [key: string]: unknown }; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getRuntimeCapabilities": { readonly method: "GET"; readonly path: "/api/v1/runtime/capabilities"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["RuntimeCapabilities"] }
    readonly "getApiV1ServerMonitor": { readonly method: "GET"; readonly path: "/api/v1/server-monitor"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: { readonly [key: string]: unknown } | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SetConfig": { readonly method: "GET"; readonly path: "/api/v1/set-config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: { readonly [key: string]: unknown } } | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1SetConfig": { readonly method: "PUT"; readonly path: "/api/v1/set-config"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: ReadonlyArray<components['schemas']["dto.GetSetSysConfigReq"]>; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysApi": { readonly method: "GET"; readonly path: "/api/v1/sys-api"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "name"?: string; readonly "title"?: string; readonly "path"?: string; readonly "action"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: components['schemas']["response.Page"] & { readonly "list"?: ReadonlyArray<components['schemas']["go-admin_app_admin_models.SysApi"]> } } | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysApiId": { readonly method: "GET"; readonly path: "/api/v1/sys-api/{id}"; readonly pathParameters: { readonly "id"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] & { readonly "data"?: components['schemas']["go-admin_app_admin_models.SysApi"] } | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1SysApiId": { readonly method: "PUT"; readonly path: "/api/v1/sys-api/{id}"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysApiUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1SysLoginLog": { readonly method: "DELETE"; readonly path: "/api/v1/sys-login-log"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysLoginLogDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysLoginLog": { readonly method: "GET"; readonly path: "/api/v1/sys-login-log"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "username"?: string; readonly "ipaddr"?: string; readonly "loginLocation"?: string; readonly "status"?: string; readonly "beginTime"?: string; readonly "endTime"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysLoginLogId": { readonly method: "GET"; readonly path: "/api/v1/sys-login-log/{id}"; readonly pathParameters: { readonly "id"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1SysOperaLog": { readonly method: "DELETE"; readonly path: "/api/v1/sys-opera-log"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysOperaLogDeleteReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysOperaLog": { readonly method: "GET"; readonly path: "/api/v1/sys-opera-log"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "title"?: string; readonly "method"?: string; readonly "requestMethod"?: string; readonly "operUrl"?: string; readonly "operIp"?: string; readonly "status"?: string; readonly "beginTime"?: string; readonly "endTime"?: string }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysOperaLogId": { readonly method: "GET"; readonly path: "/api/v1/sys-opera-log/{id}"; readonly pathParameters: { readonly "id"?: string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1SysUser": { readonly method: "DELETE"; readonly path: "/api/v1/sys-user"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysUser": { readonly method: "GET"; readonly path: "/api/v1/sys-user"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "username"?: string }; readonly requestBody: unknown; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1SysUser": { readonly method: "POST"; readonly path: "/api/v1/sys-user"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysUserInsertReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1SysUser": { readonly method: "PUT"; readonly path: "/api/v1/sys-user"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.SysUserUpdateReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysUserId": { readonly method: "GET"; readonly path: "/api/v1/sys-user/{id}"; readonly pathParameters: { readonly "id": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getGeneratedTableInfo": { readonly method: "GET"; readonly path: "/api/v1/sys/tables/info"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1SysTablesInfo": { readonly method: "POST"; readonly path: "/api/v1/sys/tables/info"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "tables"?: string }; readonly requestBody: unknown; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1SysTablesInfo": { readonly method: "PUT"; readonly path: "/api/v1/sys/tables/info"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["tools.SysTables"]; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteApiV1SysTablesInfoTableId": { readonly method: "DELETE"; readonly path: "/api/v1/sys/tables/info/{tableId}"; readonly pathParameters: { readonly "tableId": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: string | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysTablesInfoTableId": { readonly method: "GET"; readonly path: "/api/v1/sys/tables/info/{tableId}"; readonly pathParameters: { readonly "tableId": number }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1SysTablesPage": { readonly method: "GET"; readonly path: "/api/v1/sys/tables/page"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: { readonly "tableName"?: string; readonly "pageSize"?: number; readonly "pageIndex"?: number }; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "deleteJobs": { readonly method: "DELETE"; readonly path: "/api/v1/sysjob"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "listJobs": { readonly method: "GET"; readonly path: "/api/v1/sysjob"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "createJob": { readonly method: "POST"; readonly path: "/api/v1/sysjob"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: { readonly [key: string]: unknown }; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "updateJob": { readonly method: "PUT"; readonly path: "/api/v1/sysjob"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: { readonly [key: string]: unknown }; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getJob": { readonly method: "GET"; readonly path: "/api/v1/sysjob/{id}"; readonly pathParameters: { readonly "id": string }; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "postApiV1UserAvatar": { readonly method: "POST"; readonly path: "/api/v1/user/avatar"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getApiV1UserProfile": { readonly method: "GET"; readonly path: "/api/v1/user/profile"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1UserPwdReset": { readonly method: "PUT"; readonly path: "/api/v1/user/pwd/reset"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.ResetSysUserPwdReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1UserPwdSet": { readonly method: "PUT"; readonly path: "/api/v1/user/pwd/set"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.PassWord"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "putApiV1UserStatus": { readonly method: "PUT"; readonly path: "/api/v1/user/status"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: components['schemas']["dto.UpdateSysUserStatusReq"]; readonly response: components['schemas']["response.Response"] | components['schemas']["ApiErrorEnvelope"] }
    readonly "getLiveness": { readonly method: "GET"; readonly path: "/health/live"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["OperationalStatus"] }
    readonly "getReadiness": { readonly method: "GET"; readonly path: "/health/ready"; readonly pathParameters: Readonly<Record<string, never>>; readonly query: Readonly<Record<string, never>>; readonly requestBody: unknown; readonly response: components['schemas']["OperationalStatus"] }
}

export interface paths {
    readonly "/api/v1/app-config": { readonly "get": operations["getApiV1AppConfig"] }
    readonly "/api/v1/captcha": { readonly "get": operations["getApiV1Captcha"] }
    readonly "/api/v1/config": { readonly "delete": operations["deleteApiV1Config"]; readonly "get": operations["getApiV1Config"]; readonly "post": operations["postApiV1Config"] }
    readonly "/api/v1/config/{id}": { readonly "get": operations["getApiV1ConfigId"]; readonly "put": operations["putApiV1ConfigId"] }
    readonly "/api/v1/configKey/{configKey}": { readonly "get": operations["getConfigByKey"] }
    readonly "/api/v1/db/columns/page": { readonly "get": operations["getApiV1DbColumnsPage"] }
    readonly "/api/v1/db/tables/page": { readonly "get": operations["getApiV1DbTablesPage"] }
    readonly "/api/v1/demo-product": { readonly "delete": operations["deleteDemoProducts"]; readonly "get": operations["listDemoProducts"]; readonly "post": operations["createDemoProduct"] }
    readonly "/api/v1/demo-product/{id}": { readonly "get": operations["getDemoProduct"]; readonly "put": operations["updateDemoProduct"] }
    readonly "/api/v1/dept": { readonly "delete": operations["deleteApiV1Dept"]; readonly "get": operations["getApiV1Dept"]; readonly "post": operations["postApiV1Dept"] }
    readonly "/api/v1/dept/{id}": { readonly "get": operations["getApiV1DeptId"]; readonly "put": operations["putApiV1DeptId"] }
    readonly "/api/v1/deptTree": { readonly "get": operations["getDepartmentTree"] }
    readonly "/api/v1/dict-data/option-select": { readonly "get": operations["getApiV1DictDataOptionSelect"] }
    readonly "/api/v1/dict/data": { readonly "delete": operations["deleteApiV1DictData"]; readonly "get": operations["getApiV1DictData"]; readonly "post": operations["postApiV1DictData"] }
    readonly "/api/v1/dict/data/{dictCode}": { readonly "get": operations["getApiV1DictDataDictCode"]; readonly "put": operations["putApiV1DictDataDictCode"] }
    readonly "/api/v1/dict/type": { readonly "delete": operations["deleteApiV1DictType"]; readonly "get": operations["getApiV1DictType"]; readonly "post": operations["postApiV1DictType"] }
    readonly "/api/v1/dict/type-option-select": { readonly "get": operations["getApiV1DictTypeOptionSelect"] }
    readonly "/api/v1/dict/type/{id}": { readonly "get": operations["getApiV1DictTypeId"]; readonly "put": operations["putApiV1DictTypeId"] }
    readonly "/api/v1/gen/apitofile/{tableId}": { readonly "get": operations["generateAPIFile"] }
    readonly "/api/v1/gen/preview/{tableId}": { readonly "get": operations["previewGeneratedCode"] }
    readonly "/api/v1/gen/tabletree": { readonly "get": operations["getGeneratedTableTree"] }
    readonly "/api/v1/gen/todb/{tableId}": { readonly "get": operations["generateMenuAndAPI"] }
    readonly "/api/v1/gen/toproject/{tableId}": { readonly "get": operations["generateCodeToProject"] }
    readonly "/api/v1/getinfo": { readonly "get": operations["getApiV1Getinfo"] }
    readonly "/api/v1/health": { readonly "get": operations["getLegacyHealth"] }
    readonly "/api/v1/job/remove/{id}": { readonly "get": operations["removeJob"] }
    readonly "/api/v1/job/start/{id}": { readonly "get": operations["startJob"] }
    readonly "/api/v1/login": { readonly "post": operations["postApiV1Login"] }
    readonly "/api/v1/logout": { readonly "post": operations["postApiV1Logout"] }
    readonly "/api/v1/menu": { readonly "delete": operations["deleteApiV1Menu"]; readonly "get": operations["getApiV1Menu"]; readonly "post": operations["postApiV1Menu"] }
    readonly "/api/v1/menu/{id}": { readonly "get": operations["getApiV1MenuId"]; readonly "put": operations["putApiV1MenuId"] }
    readonly "/api/v1/menurole": { readonly "get": operations["getApiV1Menurole"] }
    readonly "/api/v1/metrics": { readonly "get": operations["getMetrics"] }
    readonly "/api/v1/post": { readonly "delete": operations["deleteApiV1Post"]; readonly "get": operations["getApiV1Post"]; readonly "post": operations["postApiV1Post"] }
    readonly "/api/v1/post/{id}": { readonly "get": operations["getApiV1PostId"]; readonly "put": operations["putApiV1PostId"] }
    readonly "/api/v1/public/uploadFile": { readonly "post": operations["postApiV1PublicUploadFile"] }
    readonly "/api/v1/role": { readonly "delete": operations["deleteApiV1Role"]; readonly "get": operations["getApiV1Role"]; readonly "post": operations["postApiV1Role"] }
    readonly "/api/v1/role-status": { readonly "put": operations["putApiV1RoleStatus"] }
    readonly "/api/v1/role/{id}": { readonly "get": operations["getApiV1RoleId"]; readonly "put": operations["putApiV1RoleId"] }
    readonly "/api/v1/roleDeptTreeselect/{roleId}": { readonly "get": operations["getRoleDepartmentTree"] }
    readonly "/api/v1/roleMenuTreeselect/{roleId}": { readonly "get": operations["getApiV1RoleMenuTreeselectRoleId"] }
    readonly "/api/v1/roledatascope": { readonly "put": operations["updateRoleDataScope"] }
    readonly "/api/v1/runtime/capabilities": { readonly "get": operations["getRuntimeCapabilities"] }
    readonly "/api/v1/server-monitor": { readonly "get": operations["getApiV1ServerMonitor"] }
    readonly "/api/v1/set-config": { readonly "get": operations["getApiV1SetConfig"]; readonly "put": operations["putApiV1SetConfig"] }
    readonly "/api/v1/sys-api": { readonly "get": operations["getApiV1SysApi"] }
    readonly "/api/v1/sys-api/{id}": { readonly "get": operations["getApiV1SysApiId"]; readonly "put": operations["putApiV1SysApiId"] }
    readonly "/api/v1/sys-login-log": { readonly "delete": operations["deleteApiV1SysLoginLog"]; readonly "get": operations["getApiV1SysLoginLog"] }
    readonly "/api/v1/sys-login-log/{id}": { readonly "get": operations["getApiV1SysLoginLogId"] }
    readonly "/api/v1/sys-opera-log": { readonly "delete": operations["deleteApiV1SysOperaLog"]; readonly "get": operations["getApiV1SysOperaLog"] }
    readonly "/api/v1/sys-opera-log/{id}": { readonly "get": operations["getApiV1SysOperaLogId"] }
    readonly "/api/v1/sys-user": { readonly "delete": operations["deleteApiV1SysUser"]; readonly "get": operations["getApiV1SysUser"]; readonly "post": operations["postApiV1SysUser"]; readonly "put": operations["putApiV1SysUser"] }
    readonly "/api/v1/sys-user/{id}": { readonly "get": operations["getApiV1SysUserId"] }
    readonly "/api/v1/sys/tables/info": { readonly "get": operations["getGeneratedTableInfo"]; readonly "post": operations["postApiV1SysTablesInfo"]; readonly "put": operations["putApiV1SysTablesInfo"] }
    readonly "/api/v1/sys/tables/info/{tableId}": { readonly "delete": operations["deleteApiV1SysTablesInfoTableId"]; readonly "get": operations["getApiV1SysTablesInfoTableId"] }
    readonly "/api/v1/sys/tables/page": { readonly "get": operations["getApiV1SysTablesPage"] }
    readonly "/api/v1/sysjob": { readonly "delete": operations["deleteJobs"]; readonly "get": operations["listJobs"]; readonly "post": operations["createJob"]; readonly "put": operations["updateJob"] }
    readonly "/api/v1/sysjob/{id}": { readonly "get": operations["getJob"] }
    readonly "/api/v1/user/avatar": { readonly "post": operations["postApiV1UserAvatar"] }
    readonly "/api/v1/user/profile": { readonly "get": operations["getApiV1UserProfile"] }
    readonly "/api/v1/user/pwd/reset": { readonly "put": operations["putApiV1UserPwdReset"] }
    readonly "/api/v1/user/pwd/set": { readonly "put": operations["putApiV1UserPwdSet"] }
    readonly "/api/v1/user/status": { readonly "put": operations["putApiV1UserStatus"] }
    readonly "/health/live": { readonly "get": operations["getLiveness"] }
    readonly "/health/ready": { readonly "get": operations["getReadiness"] }
}
