// Package organizationtransport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package organizationtransport

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ProblemCategory.
const (
	Authentication ProblemCategory = "authentication"
	Authorization  ProblemCategory = "authorization"
	Conflict       ProblemCategory = "conflict"
	Internal       ProblemCategory = "internal"
	NotFound       ProblemCategory = "not_found"
	Validation     ProblemCategory = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCategory enum.
func (e ProblemCategory) Valid() bool {
	switch e {
	case Authentication:
		return true
	case Authorization:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// Department defines model for Department.
type Department struct {
	Id        Identifier  `json:"id"`
	Key       StableKey   `json:"key"`
	Name      string      `json:"name"`
	ParentId  *Identifier `json:"parentId,omitempty"`
	Protected bool        `json:"protected"`
	SortOrder int         `json:"sortOrder"`
}

// DepartmentInput defines model for DepartmentInput.
type DepartmentInput struct {
	Key       StableKey  `json:"key"`
	Name      string     `json:"name"`
	ParentId  Identifier `json:"parentId"`
	SortOrder int        `json:"sortOrder"`
}

// Identifier defines model for Identifier.
type Identifier = string

// Position defines model for Position.
type Position struct {
	DepartmentId Identifier `json:"departmentId"`
	Enabled      bool       `json:"enabled"`
	Id           Identifier `json:"id"`
	Key          StableKey  `json:"key"`
	Name         string     `json:"name"`
	Protected    bool       `json:"protected"`
}

// PositionInput defines model for PositionInput.
type PositionInput struct {
	DepartmentId Identifier `json:"departmentId"`
	Enabled      bool       `json:"enabled"`
	Key          StableKey  `json:"key"`
	Name         string     `json:"name"`
}

// PositionPage defines model for PositionPage.
type PositionPage struct {
	Rows  []Position `json:"rows"`
	Total int        `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	Category ProblemCategory `json:"category"`
	Code     string          `json:"code"`

	// Detail Safe client-facing context without infrastructure details.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`

	// Type Stable problem type identifier.
	Type       string                 `json:"type"`
	Violations *[]ValidationViolation `json:"violations,omitempty"`
}

// ProblemCategory defines model for Problem.Category.
type ProblemCategory string

// StableKey defines model for StableKey.
type StableKey = string

// ValidationViolation defines model for ValidationViolation.
type ValidationViolation struct {
	Field   string  `json:"field"`
	Message *string `json:"message,omitempty"`
	Rule    string  `json:"rule"`
}

// DepartmentId defines model for DepartmentId.
type DepartmentId = Identifier

// PositionId defines model for PositionId.
type PositionId = Identifier

// AuthenticationProblem defines model for AuthenticationProblem.
type AuthenticationProblem = Problem

// AuthorizationProblem defines model for AuthorizationProblem.
type AuthorizationProblem = Problem

// ConflictProblem defines model for ConflictProblem.
type ConflictProblem = Problem

// InternalProblem defines model for InternalProblem.
type InternalProblem = Problem

// NotFoundProblem defines model for NotFoundProblem.
type NotFoundProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// ListOrganizationPositionsParams defines parameters for ListOrganizationPositions.
type ListOrganizationPositionsParams struct {
	Search   *string `form:"search,omitempty" json:"search,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateOrganizationDepartmentJSONRequestBody defines body for CreateOrganizationDepartment for application/json ContentType.
type CreateOrganizationDepartmentJSONRequestBody = DepartmentInput

// UpdateOrganizationDepartmentJSONRequestBody defines body for UpdateOrganizationDepartment for application/json ContentType.
type UpdateOrganizationDepartmentJSONRequestBody = DepartmentInput

// CreateOrganizationPositionJSONRequestBody defines body for CreateOrganizationPosition for application/json ContentType.
type CreateOrganizationPositionJSONRequestBody = PositionInput

// UpdateOrganizationPositionJSONRequestBody defines body for UpdateOrganizationPosition for application/json ContentType.
type UpdateOrganizationPositionJSONRequestBody = PositionInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListOrganizationDepartments List the authorized department tree
	// (GET /organization/departments)
	ListOrganizationDepartments(w http.ResponseWriter, r *http.Request)
	// CreateOrganizationDepartment Create a department
	// (POST /organization/departments)
	CreateOrganizationDepartment(w http.ResponseWriter, r *http.Request)
	// DeleteOrganizationDepartment Delete an unprotected and unreferenced department
	// (DELETE /organization/departments/{departmentId})
	DeleteOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId)
	// UpdateOrganizationDepartment Update a department and its parent relationship
	// (PATCH /organization/departments/{departmentId})
	UpdateOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId)
	// ListOrganizationPositions List positions
	// (GET /organization/positions)
	ListOrganizationPositions(w http.ResponseWriter, r *http.Request, params ListOrganizationPositionsParams)
	// CreateOrganizationPosition Create a position in a department
	// (POST /organization/positions)
	CreateOrganizationPosition(w http.ResponseWriter, r *http.Request)
	// DeleteOrganizationPosition Delete an unprotected position
	// (DELETE /organization/positions/{positionId})
	DeleteOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId)
	// UpdateOrganizationPosition Update a position and its department relationship
	// (PATCH /organization/positions/{positionId})
	UpdateOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListOrganizationDepartments List the authorized department tree
// (GET /organization/departments)
func (_ Unimplemented) ListOrganizationDepartments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrganizationDepartment Create a department
// (POST /organization/departments)
func (_ Unimplemented) CreateOrganizationDepartment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteOrganizationDepartment Delete an unprotected and unreferenced department
// (DELETE /organization/departments/{departmentId})
func (_ Unimplemented) DeleteOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateOrganizationDepartment Update a department and its parent relationship
// (PATCH /organization/departments/{departmentId})
func (_ Unimplemented) UpdateOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListOrganizationPositions List positions
// (GET /organization/positions)
func (_ Unimplemented) ListOrganizationPositions(w http.ResponseWriter, r *http.Request, params ListOrganizationPositionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrganizationPosition Create a position in a department
// (POST /organization/positions)
func (_ Unimplemented) CreateOrganizationPosition(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteOrganizationPosition Delete an unprotected position
// (DELETE /organization/positions/{positionId})
func (_ Unimplemented) DeleteOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateOrganizationPosition Update a position and its department relationship
// (PATCH /organization/positions/{positionId})
func (_ Unimplemented) UpdateOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrganizationDepartments operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizationDepartments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizationDepartments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganizationDepartment operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganizationDepartment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganizationDepartment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganizationDepartment operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganizationDepartment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "departmentId" -------------
	var departmentId DepartmentId

	err = runtime.BindStyledParameterWithOptions("simple", "departmentId", chi.URLParam(r, "departmentId"), &departmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "departmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganizationDepartment(w, r, departmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganizationDepartment operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganizationDepartment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "departmentId" -------------
	var departmentId DepartmentId

	err = runtime.BindStyledParameterWithOptions("simple", "departmentId", chi.URLParam(r, "departmentId"), &departmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "departmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganizationDepartment(w, r, departmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizationPositions operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizationPositions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationPositionsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizationPositions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganizationPosition operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganizationPosition(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganizationPosition(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganizationPosition operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganizationPosition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "positionId" -------------
	var positionId PositionId

	err = runtime.BindStyledParameterWithOptions("simple", "positionId", chi.URLParam(r, "positionId"), &positionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "positionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganizationPosition(w, r, positionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganizationPosition operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganizationPosition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "positionId" -------------
	var positionId PositionId

	err = runtime.BindStyledParameterWithOptions("simple", "positionId", chi.URLParam(r, "positionId"), &positionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "positionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganizationPosition(w, r, positionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/organization/departments", wrapper.ListOrganizationDepartments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/organization/departments", wrapper.CreateOrganizationDepartment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/organization/departments/{departmentId}", wrapper.DeleteOrganizationDepartment)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/organization/departments/{departmentId}", wrapper.UpdateOrganizationDepartment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/organization/positions", wrapper.ListOrganizationPositions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/organization/positions", wrapper.CreateOrganizationPosition)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/organization/positions/{positionId}", wrapper.DeleteOrganizationPosition)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/organization/positions/{positionId}", wrapper.UpdateOrganizationPosition)
	})

	return r
}

type AuthenticationProblemApplicationProblemPlusJSONResponse Problem

type AuthorizationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type AuthorizationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers AuthorizationProblemResponseHeaders
}

type ConflictProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type ConflictProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictProblemResponseHeaders
}

type InternalProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type InternalProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalProblemResponseHeaders
}

type NotFoundProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type NotFoundProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers NotFoundProblemResponseHeaders
}

type ValidationProblemResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}
type ValidationProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ValidationProblemResponseHeaders
}

type ListOrganizationDepartmentsRequestObject struct {
}

type ListOrganizationDepartmentsResponseObject interface {
	VisitListOrganizationDepartmentsResponse(w http.ResponseWriter) error
}

type ListOrganizationDepartments200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type ListOrganizationDepartments200JSONResponse struct {
	Body    []Department
	Headers ListOrganizationDepartments200ResponseHeaders
}

func (response ListOrganizationDepartments200JSONResponse) VisitListOrganizationDepartmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationDepartments401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationDepartments401ApplicationProblemPlusJSONResponse) VisitListOrganizationDepartmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationDepartments403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationDepartments403ApplicationProblemPlusJSONResponse) VisitListOrganizationDepartmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationDepartments500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationDepartments500ApplicationProblemPlusJSONResponse) VisitListOrganizationDepartmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartmentRequestObject struct {
	Body *CreateOrganizationDepartmentJSONRequestBody
}

type CreateOrganizationDepartmentResponseObject interface {
	VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error
}

type CreateOrganizationDepartment201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type CreateOrganizationDepartment201JSONResponse struct {
	Body    Department
	Headers CreateOrganizationDepartment201ResponseHeaders
}

func (response CreateOrganizationDepartment201JSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment400ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment401ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment403ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment404ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment409ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationDepartment500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationDepartment500ApplicationProblemPlusJSONResponse) VisitCreateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationDepartmentRequestObject struct {
	DepartmentId DepartmentId `json:"departmentId"`
}

type DeleteOrganizationDepartmentResponseObject interface {
	VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error
}

type DeleteOrganizationDepartment204ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type DeleteOrganizationDepartment204Response struct {
	Headers DeleteOrganizationDepartment204ResponseHeaders
}

func (response DeleteOrganizationDepartment204Response) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(204)
	return nil
}

type DeleteOrganizationDepartment401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationDepartment401ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationDepartment403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationDepartment403ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationDepartment404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationDepartment404ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationDepartment409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationDepartment409ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationDepartment500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationDepartment500ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartmentRequestObject struct {
	DepartmentId DepartmentId `json:"departmentId"`
	Body         *UpdateOrganizationDepartmentJSONRequestBody
}

type UpdateOrganizationDepartmentResponseObject interface {
	VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error
}

type UpdateOrganizationDepartment200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type UpdateOrganizationDepartment200JSONResponse struct {
	Body    Department
	Headers UpdateOrganizationDepartment200ResponseHeaders
}

func (response UpdateOrganizationDepartment200JSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment400ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment401ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment403ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment404ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment409ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationDepartment500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationDepartment500ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationDepartmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationPositionsRequestObject struct {
	Params ListOrganizationPositionsParams
}

type ListOrganizationPositionsResponseObject interface {
	VisitListOrganizationPositionsResponse(w http.ResponseWriter) error
}

type ListOrganizationPositions200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type ListOrganizationPositions200JSONResponse struct {
	Body    PositionPage
	Headers ListOrganizationPositions200ResponseHeaders
}

func (response ListOrganizationPositions200JSONResponse) VisitListOrganizationPositionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationPositions400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationPositions400ApplicationProblemPlusJSONResponse) VisitListOrganizationPositionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationPositions401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationPositions401ApplicationProblemPlusJSONResponse) VisitListOrganizationPositionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationPositions403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationPositions403ApplicationProblemPlusJSONResponse) VisitListOrganizationPositionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrganizationPositions500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response ListOrganizationPositions500ApplicationProblemPlusJSONResponse) VisitListOrganizationPositionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPositionRequestObject struct {
	Body *CreateOrganizationPositionJSONRequestBody
}

type CreateOrganizationPositionResponseObject interface {
	VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error
}

type CreateOrganizationPosition201ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type CreateOrganizationPosition201JSONResponse struct {
	Body    Position
	Headers CreateOrganizationPosition201ResponseHeaders
}

func (response CreateOrganizationPosition201JSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition400ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition401ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition403ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition404ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition409ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrganizationPosition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response CreateOrganizationPosition500ApplicationProblemPlusJSONResponse) VisitCreateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationPositionRequestObject struct {
	PositionId PositionId `json:"positionId"`
}

type DeleteOrganizationPositionResponseObject interface {
	VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error
}

type DeleteOrganizationPosition204ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type DeleteOrganizationPosition204Response struct {
	Headers DeleteOrganizationPosition204ResponseHeaders
}

func (response DeleteOrganizationPosition204Response) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(204)
	return nil
}

type DeleteOrganizationPosition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationPosition401ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationPosition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationPosition403ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationPosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationPosition404ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationPosition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationPosition409ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrganizationPosition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response DeleteOrganizationPosition500ApplicationProblemPlusJSONResponse) VisitDeleteOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPositionRequestObject struct {
	PositionId PositionId `json:"positionId"`
	Body       *UpdateOrganizationPositionJSONRequestBody
}

type UpdateOrganizationPositionResponseObject interface {
	VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error
}

type UpdateOrganizationPosition200ResponseHeaders struct {
	SetCookie  *string
	XCSRFToken *string
}

type UpdateOrganizationPosition200JSONResponse struct {
	Body    Position
	Headers UpdateOrganizationPosition200ResponseHeaders
}

func (response UpdateOrganizationPosition200JSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition400ApplicationProblemPlusJSONResponse struct {
	ValidationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition400ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition401ApplicationProblemPlusJSONResponse struct {
	AuthenticationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition401ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition403ApplicationProblemPlusJSONResponse struct {
	AuthorizationProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition403ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition404ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition409ApplicationProblemPlusJSONResponse struct {
	ConflictProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition409ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrganizationPosition500ApplicationProblemPlusJSONResponse struct {
	InternalProblemApplicationProblemPlusJSONResponse
}

func (response UpdateOrganizationPosition500ApplicationProblemPlusJSONResponse) VisitUpdateOrganizationPositionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XCSRFToken != nil {
		w.Header().Set("X-CSRF-Token", fmt.Sprint(*response.Headers.XCSRFToken))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListOrganizationDepartments List the authorized department tree
	// (GET /organization/departments)
	ListOrganizationDepartments(ctx context.Context, request ListOrganizationDepartmentsRequestObject) (ListOrganizationDepartmentsResponseObject, error)
	// CreateOrganizationDepartment Create a department
	// (POST /organization/departments)
	CreateOrganizationDepartment(ctx context.Context, request CreateOrganizationDepartmentRequestObject) (CreateOrganizationDepartmentResponseObject, error)
	// DeleteOrganizationDepartment Delete an unprotected and unreferenced department
	// (DELETE /organization/departments/{departmentId})
	DeleteOrganizationDepartment(ctx context.Context, request DeleteOrganizationDepartmentRequestObject) (DeleteOrganizationDepartmentResponseObject, error)
	// UpdateOrganizationDepartment Update a department and its parent relationship
	// (PATCH /organization/departments/{departmentId})
	UpdateOrganizationDepartment(ctx context.Context, request UpdateOrganizationDepartmentRequestObject) (UpdateOrganizationDepartmentResponseObject, error)
	// ListOrganizationPositions List positions
	// (GET /organization/positions)
	ListOrganizationPositions(ctx context.Context, request ListOrganizationPositionsRequestObject) (ListOrganizationPositionsResponseObject, error)
	// CreateOrganizationPosition Create a position in a department
	// (POST /organization/positions)
	CreateOrganizationPosition(ctx context.Context, request CreateOrganizationPositionRequestObject) (CreateOrganizationPositionResponseObject, error)
	// DeleteOrganizationPosition Delete an unprotected position
	// (DELETE /organization/positions/{positionId})
	DeleteOrganizationPosition(ctx context.Context, request DeleteOrganizationPositionRequestObject) (DeleteOrganizationPositionResponseObject, error)
	// UpdateOrganizationPosition Update a position and its department relationship
	// (PATCH /organization/positions/{positionId})
	UpdateOrganizationPosition(ctx context.Context, request UpdateOrganizationPositionRequestObject) (UpdateOrganizationPositionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOrganizationDepartments operation middleware
func (sh *strictHandler) ListOrganizationDepartments(w http.ResponseWriter, r *http.Request) {
	var request ListOrganizationDepartmentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizationDepartments(ctx, request.(ListOrganizationDepartmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizationDepartments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationDepartmentsResponseObject); ok {
		if err := validResponse.VisitListOrganizationDepartmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganizationDepartment operation middleware
func (sh *strictHandler) CreateOrganizationDepartment(w http.ResponseWriter, r *http.Request) {
	var request CreateOrganizationDepartmentRequestObject

	var body CreateOrganizationDepartmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganizationDepartment(ctx, request.(CreateOrganizationDepartmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganizationDepartment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationDepartmentResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationDepartmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrganizationDepartment operation middleware
func (sh *strictHandler) DeleteOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId) {
	var request DeleteOrganizationDepartmentRequestObject

	request.DepartmentId = departmentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrganizationDepartment(ctx, request.(DeleteOrganizationDepartmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrganizationDepartment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrganizationDepartmentResponseObject); ok {
		if err := validResponse.VisitDeleteOrganizationDepartmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrganizationDepartment operation middleware
func (sh *strictHandler) UpdateOrganizationDepartment(w http.ResponseWriter, r *http.Request, departmentId DepartmentId) {
	var request UpdateOrganizationDepartmentRequestObject

	request.DepartmentId = departmentId

	var body UpdateOrganizationDepartmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrganizationDepartment(ctx, request.(UpdateOrganizationDepartmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrganizationDepartment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrganizationDepartmentResponseObject); ok {
		if err := validResponse.VisitUpdateOrganizationDepartmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrganizationPositions operation middleware
func (sh *strictHandler) ListOrganizationPositions(w http.ResponseWriter, r *http.Request, params ListOrganizationPositionsParams) {
	var request ListOrganizationPositionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizationPositions(ctx, request.(ListOrganizationPositionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizationPositions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationPositionsResponseObject); ok {
		if err := validResponse.VisitListOrganizationPositionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganizationPosition operation middleware
func (sh *strictHandler) CreateOrganizationPosition(w http.ResponseWriter, r *http.Request) {
	var request CreateOrganizationPositionRequestObject

	var body CreateOrganizationPositionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganizationPosition(ctx, request.(CreateOrganizationPositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganizationPosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationPositionResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationPositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrganizationPosition operation middleware
func (sh *strictHandler) DeleteOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId) {
	var request DeleteOrganizationPositionRequestObject

	request.PositionId = positionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrganizationPosition(ctx, request.(DeleteOrganizationPositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrganizationPosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrganizationPositionResponseObject); ok {
		if err := validResponse.VisitDeleteOrganizationPositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrganizationPosition operation middleware
func (sh *strictHandler) UpdateOrganizationPosition(w http.ResponseWriter, r *http.Request, positionId PositionId) {
	var request UpdateOrganizationPositionRequestObject

	request.PositionId = positionId

	var body UpdateOrganizationPositionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrganizationPosition(ctx, request.(UpdateOrganizationPositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrganizationPosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrganizationPositionResponseObject); ok {
		if err := validResponse.VisitUpdateOrganizationPositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
