import { spawn, spawnSync } from 'node:child_process'
import { randomInt } from 'node:crypto'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs'
import { request as httpsRequest } from 'node:https'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { activeChildren, assertChildHealthy, CDPClient, delay, spawnTracked, terminateChild, withTimeout } from '../iam/administration/runner-support.mjs'
import { safeRunnerDiagnostic } from '../iam/administration/diagnostics.mjs'

if(process.env.GO_ADMIN_REQUIRE_GENERATOR_E2E!=='1'){console.log('GENERATOR_E2E_SKIP required opt-in is disabled');process.exit(0)}
const chromium=process.env.GO_ADMIN_TEST_CHROMIUM_EXECUTABLE
if(!chromium){console.error('GENERATOR_E2E_RUN_FAIL|Chromium is required');process.exit(1)}
const root=dirname(fileURLToPath(import.meta.url)),uiRoot=resolve(root,'../../..'),backend=resolve(uiRoot,'../go-admin-plus'),temporary=mkdtempSync(join(tmpdir(),'go-admin-generator-e2e-')),staticRoot=join(temporary,'static'),deadline=Date.now()+24*60_000
const remaining=max=>{const value=Math.min(max,deadline-Date.now());if(value<=0)throw new Error('overall deadline exceeded');return value}
const checked=(command,args,options={})=>{const value=spawnSync(command,args,{...options,encoding:'utf8',timeout:remaining(options.timeout??180_000),killSignal:'SIGKILL'});if(value.status!==0||value.error||value.signal){const output=`${value.stderr??''} ${value.stdout??''}`.slice(-4000);throw new Error(`${options.failure??'child command failed'} status=${value.status??'spawn'} signal=${value.signal??'none'} code=${value.error?.code??'none'} detail=${safeRunnerDiagnostic(output)}`)}}
const pgBin=process.env.GO_ADMIN_GENERATOR_POSTGRES_BIN?resolve(process.env.GO_ADMIN_GENERATOR_POSTGRES_BIN):undefined
const pgLib=pgBin?resolve(pgBin,'../lib'):''
const requireRegularExecutable=path=>{const info=statSync(path);if(!info.isFile()||(info.mode&0o111)===0)throw new Error('PostgreSQL tool is not a regular executable')}
const validatePostgresTools=()=>{if(!pgBin)throw new Error('GO_ADMIN_GENERATOR_POSTGRES_BIN is required without a disposable DSN');for(const name of ['initdb','pg_ctl','postgres'])requireRegularExecutable(join(pgBin,name));if(!statSync(pgLib).isDirectory())throw new Error('PostgreSQL library directory is invalid')}
const pgEnv=()=>({...process.env,DYLD_LIBRARY_PATH:pgLib});let pgStarted=false;const pgData=join(temporary,'pgdata'),pgSocket=join(temporary,'pgsocket');let pgPort=0
const startPostgres=()=>{if(process.env.GO_ADMIN_TEST_POSTGRES_DISPOSABLE_DSN)return process.env.GO_ADMIN_TEST_POSTGRES_DISPOSABLE_DSN;validatePostgresTools();checked(join(pgBin,'initdb'),['-D',pgData,'-A','trust','-U','postgres'],{env:pgEnv(),stdio:'pipe',failure:'initdb failed'});mkdirSync(pgSocket,{recursive:true,mode:0o700});for(let attempt=0;attempt<5;attempt++){pgPort=randomInt(20000,50000);const value=spawnSync(join(pgBin,'pg_ctl'),['-D',pgData,'-o',`-h '' -k ${pgSocket} -p ${pgPort} -F`,'-w','start'],{env:pgEnv(),stdio:'pipe',encoding:'utf8',timeout:remaining(30_000),killSignal:'SIGKILL'});if(value.status===0&&!value.error&&!value.signal){pgStarted=true;return `postgres://postgres@/postgres?host=${encodeURIComponent(pgSocket)}&port=${pgPort}&sslmode=disable`}}throw new Error('postgres start failed after bounded retries')}
const waitReady=async(path,child)=>{const until=Date.now()+remaining(60_000);while(Date.now()<until){if(existsSync(path))return readFileSync(path,'utf8').trim();assertChildHealthy(child,'Generator host');await delay(100)}throw new Error('Generator host readiness timed out')}
const socketFor=child=>withTimeout(new Promise((ok,fail)=>{let text='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>{text=(text+chunk).slice(-8192);const match=text.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match)ok(match[1])});child.once('error',()=>fail(new Error('Chromium start failed')));child.once('exit',()=>fail(new Error('Chromium exited early')))}),remaining(30_000),'Chromium readiness')
const websocket=url=>{const socket=new WebSocket(url);return withTimeout(new Promise((ok,fail)=>{socket.addEventListener('open',()=>ok(socket),{once:true});socket.addEventListener('error',()=>fail(new Error('CDP connection failed')),{once:true})}),remaining(15_000),'CDP connection',()=>socket.close())}
const shutdown=baseURL=>new Promise(resolvePromise=>{const request=httpsRequest(new URL('/__test/shutdown',baseURL),{method:'POST',rejectUnauthorized:false},response=>{response.resume();response.once('end',resolvePromise)});request.once('error',resolvePromise);request.end()})
const runProfile=async(profile,dsn)=>{const ready=join(temporary,profile,'ready');let host,browser,socket,cdp,baseURL,error,passed=false
  try{host=spawnTracked(spawn,'go',['test','./test/generator','-run','^TestGeneratorBrowserHarnessServer$','-count=1','-v'],{cwd:backend,env:{...process.env,GO_ADMIN_GENERATOR_E2E_SERVE:'1',GO_ADMIN_GENERATOR_E2E_PROFILE:profile,GO_ADMIN_GENERATOR_E2E_READY_FILE:ready,GO_ADMIN_GENERATOR_E2E_STATIC_DIR:staticRoot,...(profile==='postgres'?{GO_ADMIN_TEST_POSTGRES_DISPOSABLE_DSN:dsn}:{})},stdio:['ignore','pipe','pipe'],drainStdout:true,drainStderr:true});baseURL=await waitReady(ready,host);browser=spawnTracked(spawn,chromium,['--headless=new','--disable-gpu','--ignore-certificate-errors','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${join(temporary,profile,'chromium')}`,baseURL],{stdio:['ignore','ignore','pipe']});socket=await websocket(await socketFor(browser));cdp=new CDPClient(socket,10_000);let page
    for(const until=Date.now()+remaining(30_000);Date.now()<until&&!page;){const values=await cdp.send('Target.getTargets');page=values.targetInfos.find(value=>value.type==='page'&&value.url.startsWith(baseURL));if(!page)await delay(100)}if(!page)throw new Error('browser page missing');const attached=await cdp.send('Target.attachToTarget',{targetId:page.targetId,flatten:true});await cdp.send('Runtime.enable',{},attached.sessionId)
    for(const until=Date.now()+remaining(480_000);Date.now()<until;){const value=await cdp.send('Runtime.evaluate',{expression:"document.querySelector('#result')?.textContent ?? ''",returnByValue:true},attached.sessionId);const text=String(value.result.value??'');if(text.includes('GENERATOR_E2E_PASS')){passed=true;break}if(text.includes('GENERATOR_E2E_FAIL|'))throw new Error(`${profile} browser failed`);await delay(100)}if(!passed)throw new Error(`${profile} browser timed out`)
    console.log(`GENERATOR_E2E_PROFILE_PASS profile=${profile}`)
  }catch(value){error=value}finally{await terminateChild(host,()=>shutdown(baseURL),15_000);if(!error&&host?.exitCode!==0)error=new Error(`${profile} host verification failed`);await terminateChild(browser,async()=>{if(cdp)await cdp.send('Browser.close');else socket?.close()});try{socket?.close()}catch{}}if(error)throw error}
let failed=false
try{checked('pnpm',['exec','vite','build','--config',join(root,'vite.config.ts')],{cwd:uiRoot,env:{...process.env,GO_ADMIN_GENERATOR_E2E_OUT_DIR:staticRoot},stdio:'pipe',failure:'browser fixture build failed'});const dsn=startPostgres();await runProfile('sqlite','');await runProfile('postgres',dsn);const marker=join(temporary,'postgres-runtime.pass');checked('go',['test','-timeout=20m','./internal/modules/generator','-run','^TestCanonicalRendererInvokesLintAndGeneration$','-count=1'],{cwd:backend,env:{...process.env,GO_ADMIN_GENERATOR_POSTGRES_DSN:dsn,GO_ADMIN_GENERATOR_POSTGRES_MARKER:marker},stdio:'pipe',timeout:16*60_000,failure:'generated PostgreSQL runtime verification failed'});if(!existsSync(marker)||readFileSync(marker,'utf8')!=='pass')throw new Error('generated PostgreSQL runtime test was skipped');console.log('GENERATOR_E2E_PASS profiles=sqlite,postgres generated_postgres_runtime=pass')}
catch(error){failed=true;console.error(`GENERATOR_E2E_RUN_FAIL|${safeRunnerDiagnostic(error)}`)}
for(const child of activeChildren)await terminateChild(child);if(pgStarted)try{checked(join(pgBin,'pg_ctl'),['-D',pgData,'-m','fast','-w','stop'],{env:pgEnv(),stdio:'pipe',failure:'postgres stop failed'})}catch{failed=true}rmSync(temporary,{recursive:true,force:true});if(failed)process.exitCode=1
