import { createApp,h,type App,type Component } from 'vue'
import { createSettingsController,createWebSettingsClient,SettingsPage } from '@go-admin-plus/web-domain-settings'
import { createCapabilityController } from '@go-admin-plus/domain-iam/administration'
import { createSessionController } from '@go-admin-plus/domain-iam/session'
import { createWebAdministrationClient } from '@go-admin-plus/web-domain-iam/administration'
import { createWebSessionClient } from '@go-admin-plus/web-domain-iam/session'
import { SettingsRequestError,settingsPermissions,type SettingInput,type SettingsPermissionCode } from '@go-admin-plus/domain-settings'
import { createBrowserSessionFetch } from '@go-admin-plus/adapter-browser'

const result=document.querySelector<HTMLElement>('#result')!
let lastMutationStatus=0,lastProblem='',lastProblemCode=''
const observedFetch:typeof fetch=async input=>{const request=input instanceof Request?input:new Request(input);const response=await fetch(request);if(request.method!=='GET'&&new URL(request.url).pathname.startsWith('/api/settings/')){lastMutationStatus=response.status;lastProblem=response.status>=400?await response.clone().text():'';try{lastProblemCode=String((JSON.parse(lastProblem)as{code?:string}).code??'')}catch{lastProblemCode=''}}return response}
const sessionFetch=createBrowserSessionFetch(observedFetch)
const session=createSessionController(createWebSessionClient(sessionFetch,'/api'))
const capabilities=createCapabilityController(createWebAdministrationClient(sessionFetch,'/api'))
const client=createWebSettingsClient(sessionFetch,'/api')
const controller=createSettingsController(client,async()=>true,{can:(code:SettingsPermissionCode)=>capabilities.can(code),scope:()=>capabilities.state().manifest?.dataScope??null})
let app:App<Element>|null=null
const mount=()=>{app?.unmount();document.querySelector('#app')!.textContent='';app=createApp({render:()=>h(SettingsPage as Component,{controller})});app.mount('#app')}
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))
const wait=async(condition:()=>boolean,message:string)=>{const until=Date.now()+15000;while(Date.now()<until){if(condition())return;await delay(25)}throw new Error(message)}
const control=async(path:string,body?:unknown)=>{const response=await fetch(path,{method:'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(response.status!==204)throw new Error('test control failed')}
const factCount=async()=>{const response=await fetch('/__test/count');if(response.status!==200)throw new Error('test count failed');return (await response.json() as{settings:number}).settings}
const element=<T extends Element>(selector:string)=>{const value=document.querySelector<T>(selector);if(!value)throw new Error('expected interface element missing');return value}
const input=(name:string,value:string)=>{const field=element<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`);field.value=value;field.dispatchEvent(new Event('input',{bubbles:true}))}
const checked=(name:string,value:boolean)=>{const field=element<HTMLInputElement>(`[name="${name}"]`);if(field.checked!==value)field.click()}
const click=(testId:string)=>element<HTMLButtonElement>(`[data-testid="${testId}"]`).click()
const createSetting=async(key:string,label:string,value:string)=>{click('open-setting-form');await wait(()=>document.querySelector('[data-testid="setting-form"]')!==null,'setting form did not open');input('setting-key',key);input('setting-label',label);input('setting-value',value);click('save-setting');await wait(()=>controller.settings.snapshot().rows.some(row=>row.key===key),'setting create failed')}
const listBusiness=()=>client.listSettings('business',{search:'',page:1,pageSize:100})
const assertSensitiveRejected=async(inputValue:SettingInput,marker:string)=>{const before=await listBusiness();lastMutationStatus=0;lastProblem='';try{await client.createSetting(inputValue);throw new Error('sensitive mutation succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='validation')throw error}const after=await listBusiness();if(lastMutationStatus!==400||lastProblem.includes(marker)||after.total!==before.total||after.rows.some(row=>row.key===inputValue.key)||document.body.textContent?.includes(marker))throw new Error('sensitive rejection contract failed')}
let stage='startup'

try{
  await session.login({username:'admin',password:'administrator password'})
  if(session.state().status!=='authenticated'||document.cookie.includes('__Host-go-admin-session'))throw new Error('login contract failed')
  await capabilities.refresh();for(const code of Object.values(settingsPermissions))if(!capabilities.can(code))throw new Error('settings capability missing')
  mount();await wait(()=>!controller.settings.snapshot().loading&&document.querySelector('[data-testid="open-setting-form"]')!==null,'settings page did not load')

  await createSetting('shop.title','商店标题','Public title')
  click('edit-setting-shop.title');await wait(()=>element<HTMLInputElement>('[name="setting-key"]').value==='shop.title','setting edit did not open');input('setting-value','Updated title');click('save-setting');await wait(()=>controller.settings.snapshot().rows.some(row=>row.key==='shop.title'&&row.value==='Updated title'),'setting update failed')
  const current=controller.settings.snapshot().rows.find(row=>row.key==='shop.title')!;try{await client.updateSetting(current.id,{category:current.category,key:current.key,label:current.label,value:'stale',description:current.description,enabled:current.enabled,revision:current.revision-1});throw new Error('stale revision succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='conflict')throw error}
  for(const fixture of [{key:'literal.percent',label:'% literal'},{key:'literal.under',label:'_ literal'},{key:'literal.unicode',label:'ä Unicode'}])await client.createSetting({category:'business',key:fixture.key,label:fixture.label,value:'visible',description:'',enabled:true})
  await controller.settings.refresh();for(const search of ['%','_','ä']){input('setting-search',search);element<HTMLInputElement>('[name="setting-search"]').closest('form')!.requestSubmit();await wait(()=>controller.settings.snapshot().total===1&&controller.settings.snapshot().rows[0]?.label.includes(search)===true,'literal UI search failed')}

  click('tab-ui');await wait(()=>controller.category()==='ui','UI tab failed');await createSetting('ui.banner','Interface banner','Welcome');click('edit-setting-ui.banner');await wait(()=>element<HTMLInputElement>('[name="setting-key"]').value==='ui.banner','UI edit did not open');input('setting-value','Welcome updated');click('save-setting');await wait(()=>controller.settings.snapshot().rows.some(row=>row.value==='Welcome updated'),'UI update failed');click('delete-setting-ui.banner');await wait(()=>controller.settings.snapshot().total===0,'UI delete failed')
  click('tab-business');await wait(()=>controller.category()==='business','business tab failed');await control('/__test/restart');await controller.settings.refresh();if(!controller.settings.snapshot().rows.some(row=>row.key==='shop.title'))throw new Error('restart persistence failed')

  stage='sensitive-direct';await assertSensitiveRejected({category:'business',key:'private-key',label:'Public label',value:'ordinary',description:'',enabled:true},'private-key')
  const sensitiveValue='Bearer abcdefghijklmnop';await assertSensitiveRejected({category:'business',key:'public.credential',label:'Public label',value:sensitiveValue,description:'',enabled:true},sensitiveValue)
  stage='sensitive-ui';click('open-setting-form');await wait(()=>document.querySelector('[data-testid="setting-form"]')!==null,'sensitive setting form did not open');input('setting-key','public.ui-probe');input('setting-label','Public label');input('setting-value',sensitiveValue);click('save-setting');await wait(()=>lastMutationStatus===400&&element<HTMLInputElement>('[name="setting-key"]').value===''&&element<HTMLTextAreaElement>('[name="setting-value"]').value===''&&!document.body.textContent?.includes(sensitiveValue),'sensitive UI rejection did not clear intent');if(lastProblem.includes(sensitiveValue)||(await listBusiness()).rows.some(row=>row.key==='public.ui-probe'))throw new Error('sensitive UI rejection changed state');element<HTMLButtonElement>('[data-testid="setting-form"] [aria-label="关闭"]').click()
  stage='cleanup';click('delete-setting-shop.title');await wait(()=>!controller.settings.snapshot().rows.some(row=>row.key==='shop.title'),'business UI delete failed');for(const row of (await listBusiness()).rows)await client.deleteSetting(row.id,row.revision);await controller.settings.refresh();if(controller.settings.snapshot().total!==0)throw new Error('business cleanup failed')

  stage='dictionaries';click('tab-dictionaries');await wait(()=>document.querySelector('[data-testid="open-dictionary-form"]')!==null,'dictionary tab failed');click('open-dictionary-form');await wait(()=>document.querySelector('[data-testid="dictionary-form"]')!==null,'dictionary form did not open');input('dictionary-key','order.status');input('dictionary-name','订单状态');click('save-dictionary');await wait(()=>controller.dictionaries.snapshot().rows.some(row=>row.key==='order.status'),'dictionary create failed');click('select-dictionary-order.status');await wait(()=>document.querySelector('[data-testid="open-item-form"]')!==null,'dictionary selection failed')
  click('open-item-form');await wait(()=>document.querySelector('[data-testid="item-form"]')!==null,'item form did not open');input('item-value','paid');input('item-label','Paid');input('item-order','20');click('save-item');await wait(()=>controller.items.snapshot().rows.some(row=>row.value==='paid'),'item create failed');click('open-item-form');await wait(()=>document.querySelector('[data-testid="item-form"]')!==null,'second item form did not open');input('item-value','draft');input('item-label','Draft');input('item-order','10');checked('item-enabled',false);click('save-item');await wait(()=>controller.items.snapshot().rows.length===2,'item ordering create failed');if(controller.items.snapshot().rows.map(row=>row.value).join(',')!=='draft,paid'||!element('[data-testid="enabled-options"]').textContent?.includes('Paid')||element('[data-testid="enabled-options"]').textContent?.includes('Draft'))throw new Error('enabled option projection failed')
  const enabledOptions=await client.options('order.status');if(enabledOptions.length!==1||enabledOptions[0]?.value!=='paid')throw new Error('enabled option API projection failed')
  click('edit-item-paid');await wait(()=>element<HTMLInputElement>('[name="item-value"]').value==='paid','item edit failed');input('item-label','Paid updated');click('save-item');await wait(()=>controller.items.snapshot().rows.some(row=>row.label==='Paid updated'),'item update failed')
  click('edit-dictionary-order.status');await wait(()=>element<HTMLInputElement>('[name="dictionary-key"]').value==='order.status','dictionary edit failed');input('dictionary-name','Order status updated');checked('dictionary-enabled',false);click('save-dictionary');await wait(()=>controller.dictionary()?.name==='Order status updated'&&controller.dictionary()?.enabled===false,'dictionary update failed');const selected=controller.dictionary()!;try{await client.updateDictionary(selected.id,{key:selected.key,name:'stale',description:selected.description,enabled:selected.enabled,revision:selected.revision-1});throw new Error('dictionary stale revision succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='conflict')throw error}if(element('[data-testid="enabled-options"]').textContent?.includes('Paid'))throw new Error('disabled dictionary exposed options')
  try{await client.options('order.status');throw new Error('disabled dictionary options succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='not-found')throw error}
  click('delete-dictionary-order.status');await wait(()=>controller.failure()==='conflict','dictionary reference conflict missing')
  click('delete-item-draft');await wait(()=>!controller.items.snapshot().rows.some(row=>row.value==='draft'),'draft delete failed');click('delete-item-paid');await wait(()=>controller.items.snapshot().rows.length===0,'paid delete failed');click('delete-dictionary-order.status');await wait(()=>controller.dictionary()===null&&!controller.dictionaries.snapshot().rows.some(row=>row.key==='order.status'),'dictionary delete failed')

  stage='authorization';const beforeScope=await listBusiness();await control('/__test/scope',{scope:'self'});await capabilities.refresh();mount();await wait(()=>document.querySelector('[data-testid="open-setting-form"]')===null,'self scope controls remained');try{await client.createSetting({category:'business',key:'scope.denied',label:'Denied',value:'Denied',description:'',enabled:true});throw new Error('self scope direct write succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='forbidden')throw new Error(`scope rejection ${error instanceof SettingsRequestError?error.category:'unknown'} status ${lastMutationStatus} code ${lastProblemCode.replaceAll('_','-')}`)}await control('/__test/scope',{scope:'all'});await capabilities.refresh();if((await listBusiness()).total!==beforeScope.total)throw new Error('self scope changed state')
  await control('/__test/permissions',{enabled:false});await capabilities.refresh();mount();await wait(()=>document.querySelector('[data-testid="open-setting-form"]')===null,'revoked controls remained');try{await client.createSetting({category:'business',key:'denied.key',label:'Denied',value:'Denied',description:'',enabled:true});throw new Error('revoked direct write succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='forbidden')throw error}await control('/__test/permissions',{enabled:true});await capabilities.refresh();if((await listBusiness()).total!==beforeScope.total)throw new Error('permission revoke changed state')

  stage='csrf';const baseline=(await listBusiness()).total;const csrf=await fetch('/api/settings/values',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:'business',key:'csrf.key',label:'CSRF',value:'Rejected',description:'',enabled:true})});const problem=await csrf.json() as{code?:string};if(csrf.status!==403||problem.code!=='CSRF_REJECTED'||(await listBusiness()).total!==baseline)throw new Error('csrf rejection contract failed')
  stage='session-revoke';mount();await wait(()=>document.querySelector('[name="setting-search"]')!==null,'restored settings page missing');const beforeSessionRevoke=await factCount();await control('/__test/revoke-session');input('setting-search','session');element<HTMLInputElement>('[name="setting-search"]').closest('form')!.requestSubmit();await wait(()=>document.querySelector('[data-failure="relogin"]')!==null&&controller.settings.snapshot().rows.length===0,'session revoke did not fail closed');try{await client.createSetting({category:'business',key:'session.denied',label:'Denied',value:'Denied',description:'',enabled:true});throw new Error('revoked session write succeeded')}catch(error){if(!(error instanceof SettingsRequestError)||error.category!=='relogin')throw error}if(await factCount()!==beforeSessionRevoke)throw new Error('session revoke changed state')
  result.textContent='SETTINGS_E2E_PASS'
}catch(error){const detail=error instanceof Error?error.message:'browser assertion failed',message=/^[a-zA-Z0-9 .,:|'-]{1,140}$/.test(detail)?`${stage} ${detail}`:`${stage} browser assertion failed`;result.textContent=`SETTINGS_E2E_FAIL|${message}`}
