CREATE TABLE goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);
INSERT INTO goose_db_version (version_id, is_applied) VALUES (0, true);
INSERT INTO goose_db_version (version_id, is_applied) VALUES (1, true);
CREATE TABLE architecture_marker (
    id bigint PRIMARY KEY,
    generation text NOT NULL
);
INSERT INTO architecture_marker (id, generation) VALUES (1, 'previous-greenfield');
